require('dotenv').config();
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const path = require('path');
const mongoose = require('mongoose');
const session = require('express-session');
const MongoStore = require('connect-mongo');
const passport = require('passport');
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const rateLimit = require('express-rate-limit');

const app = express();
app.set('trust proxy', 1);

const server = http.createServer(app);

const io = new Server(server, {
    pingTimeout: 60000,
    pingInterval: 25000,
    transports: ['websocket', 'polling'],
    httpCompression: true
});

// === LIMITES DE SEGURANÇA ===
const MAX_GLOBAL_PLAYERS = 500; 
const MAX_ROOMS = 100;
const ROUND_TIME = 45; 
const TOTAL_ROUNDS = 10;
const RECONNECT_GRACE_PERIOD = 60000; // 60 segundos para voltar do WhatsApp

// ===========================================================================
// LISTA DE PALAVRAS (COLE AQUI A SUA LISTA GIGANTE)
// ===========================================================================

const WORDS = [
    // ... SUAS PALAVRAS AQUI ...
	"ABACA", "ABATA", "ABATE", "ABATI", "ABEBE", "ABECE", "ABEDO", "ABETA", "ABETE", "ABETO",
    "ABEXI", "ABICO", "ABIDO", "ABIET", "ABIGA", "ABILA", "ABITA", "ABJEO", "ABOAR", "ABOAS",
    "ABOCA", "ABOFE", "ABOIO", "ABOIS", "ABOLE", "ABOLI", "ABONA", "ABONO", "ABOOI", "ABOOU",
    "ABORA", "ABOVE", "ABRAA", "ABRAO", "ABRAR", "ABRAS", "ABREM", "ABRES", "ABREU", "ABRIL",
    "ABRIM", "ABRIR", "ABRIS", "ABRIU", "ABSTE", "ABUJE", "ABULO", "ABUNA", "ABUSA", "ABUSE",
    "ABUSO", "ABUTA", "ACABA", "ACABE", "ACABO", "ACACA", "ACAIA", "ACAIO", "ACAJU", "ACALA",
    "ACALO", "ACAMA", "ACANA", "ACAOA", "ACARA", "ACARI", "ACARO", "ACASO", "ACATA", "ACATE",
    "ACATO", "ACAVA", "ACCAO", "ACECA", "ACEDA", "ACEDE", "ACEDI", "ACEDO", "ACEFE", "ACELO",
    "ACENA", "ACENE", "ACENO", "ACERO", "ACESO", "ACETO", "ACHAI", "ACHAM", "ACHAR", "ACHAS",
    "ACHEI", "ACHEM", "ACHES", "ACHOA", "ACHOU", "ACIAN", "ACIDE", "ACIDO", "ACILA", "ACIMA",
    "ACIMO", "ACINS", "ACION", "ACIOS", "ACISO", "ACLIS", "ACMIN", "ACNES", "ACOAR", "ACOAS",
    "ACODA", "ACODE", "ACODI", "ACOES", "ACOLA", "ACOLE", "ACOLO", "ACOMP", "ACONA", "ACONE",
    "ACONS", "ACORR", "ACOTE", "ACOTO", "ACOUA", "ACOUS", "ACRAL", "ACRES", "ACROA", "ACROE",
    "ACROL", "ACRON", "ACROS", "ACSAO", "ACUAR", "ACUAS", "ACUDA", "ACUDE", "ACUDI", "ACUDO",
    "ACUEI", "ACUEM", "ACUES", "ACUFE", "ACULA", "ACULE", "ACUME", "ACUNA", "ACUOU", "ACURA",
    "ACURE", "ACURO", "ACUSO", "ACUTA", "ACUTI", "ADACA", "ADAGE", "ADAGI", "ADAIL", "ADALI",
    "ADAMA", "ADAMO", "ADAMS", "ADANA", "ADATE", "ADEAR", "ADEGA", "ADEJA", "ADEJE", "ADEJO",
    "ADELA", "ADELE", "ADELO", "ADEMA", "ADENS", "ADEQU", "ADERE", "ADERI", "ADERS", "ADESO",
    "ADEUS", "ADEVA", "ADIAM", "ADIAR", "ADIAS", "ADIBE", "ADICA", "ADIDO", "ADIEI", "ADIEM",
    "ADIES", "ADIMO", "ADINA", "ADIOE", "ADIOS", "ADIOU", "ADIRA", "ADIRI", "ADIRO", "ADITA",
    "ADITE", "ADITO", "ADIVA", "ADIVO", "ADIXA", "ADJAZ", "ADMET", "ADMIN", "ADOBE", "ADOBO",
    "ADOCA", "ADOCO", "ADOGA", "ADOLA", "ADOLO", "ADOME", "ADOMO", "ADONA", "ADONE", "ADONC",
    "ADORA", "ADORE", "ADORO", "ADOTA", "ADOTE", "ADOTO", "ADOXA", "ADOXO", "ADQUI", "ADRAR",
    "ADREI", "ADROA", "ADROS", "ADUAR", "ADUBA", "ADUBE", "ADUBO", "ADUFA", "ADUFE", "ADUFO",
    "ADUJA", "ADUJE", "ADUJO", "ADULA", "ADULE", "ADULO", "ADURO", "ADUSA", "ADUSE", "ADUSO",
    "ADUZI", "ADVEM", "ADVER", "ADVIA", "ADVIM", "ADVIR", "ADVIU", "AECIO", "AEDES", "AEDOS",
    "AEGIA", "AEGIO", "AEGIS", "AELIA", "AELIO", "AEMIO", "AEREO", "AERIA", "AETIO", "AFACA",
    "AFACO", "AFAGA", "AFAGO", "AFAMA", "AFAME", "AFAMO", "AFANA", "AFANE", "AFANO", "AFAOA",
    "AFARE", "AFARO", "AFEAR", "AFECK", "AFEIA", "AFEIO", "AFELI", "AFERE", "AFERI", "AFETA",
    "AFETE", "AFETO", "AFIAO", "AFIAR", "AFIAS", "AFICA", "AFICE", "AFICO", "AFIDO", "AFIEI",
    "AFIEM", "AFIES", "AFIGO", "AFILA", "AFILE", "AFILO", "AFIMO", "AFINA", "AFINE", "AFINO",
    "AFINS", "AFIOU", "AFIRA", "AFIRO", "AFITO", "AFIUZ", "AFLAR", "AFLAS", "AFLEU", "AFLUI",
    "AFOBA", "AFOBE", "AFOBO", "AFOFA", "AFOFE", "AFOFO", "AFOGA", "AFOGO", "AFOLA", "AFOLE",
    "AFOLO", "AFORA", "AFORE", "AFORO", "AFOXE", "AFOZA", "AFRIR", "AFROA", "AFTAS", "AGACE",
    "AGACH", "AGADA", "AGAIX", "AGAJA", "AGALE", "AGALH", "AGAMA", "AGAME", "AGAMI", "AGANA",
    "AGANE", "AGANO", "AGAPE", "AGARA", "AGARE", "AGARI", "AGARO", "AGATA", "AGATE", "AGAVE",
    "AGAZE", "AGEIS", "AGEMA", "AGEMS", "AGENO", "AGENS", "AGENT", "AGIAM", "AGIAS", "AGIDA",
    "AGIDO", "AGIMO", "AGINA", "AGINO", "AGIOS", "AGIRA", "AGITA", "AGITE", "AGITO", "AGLAS",
    "AGNAO", "AGNAT", "AGNEL", "AGNES", "AGNIS", "AGNOS", "AGNOW", "AGNUM", "AGNUS", "AGOAR",
    "AGOGE", "AGOGO", "AGOMA", "AGOME", "AGOMO", "AGORA", "AGORE", "AGORO", "AGOST", "AGRAR",
    "AGRAS", "AGRAZ", "AGREI", "AGRES", "AGRIA", "AGRIO", "AGROR", "AGROS", "AGUAI", "AGUAM",
    "AGUAR", "AGUAS", "AGUCA", "AGUCO", "AGUDA", "AGUDE", "AGUDO", "AGUEI", "AGUEM", "AGUES",
    "AGUIA", "AGUJA", "AGULH", "AGUOU", "AGURI", "AGUTI", "AIAIA", "AIALA", "AIBAO", "AIBAS",
    "AIBOS", "AICMO", "AIDAS", "AIDES", "AIDRO", "AIGUA", "AILAS", "AILOS", "AIMOL", "AINDA",
    "AINHO", "AIOIA", "AIPIM", "AIPIS", "AIPOS", "AIRAO", "AIRAR", "AIRES", "AIROL", "AIROS",
    "AIROU", "AIRUA", "AITAO", "AIUBA", "AIUCA", "AIUIO", "AIVAO", "AIVAS", "AIVES", "AIVIM",
    "AIVOS", "AJUDA", "AJUDE", "AJUDO", "AJUGA", "ALABA", "ALABE", "ALABI", "ALACA", "ALACU",
    "ALADA", "ALADO", "ALAFI", "ALAGA", "ALAGO", "ALAIS", "ALAJA", "ALAJE", "ALAJO", "ALALA",
    "ALAMO", "ALANO", "ALAOI", "ALAPA", "ALAPE", "ALAPI", "ALAPO", "ALARA", "ALARD", "ALARI",
    "ALATA", "ALAUI", "ALAVA", "ALAVE", "ALAZA", "ALBAR", "ALBAS", "ALBIS", "ALBIZ", "ALBOI",
    "ALBUM", "ALBUR", "ALCAL", "ALCAN", "ALCAR", "ALCAS", "ALCEI", "ALCEM", "ALCES", "ALCEU",
    "ALCIO", "ALCIS", "ALCOL", "ALCOR", "ALCOV", "ALCUA", "ALCUN", "ALDEA", "ALDEI", "ALDER",
    "ALDOL", "ALEIA", "ALEIS", "ALELI", "ALELO", "ALEMA", "ALEMO", "ALENA", "ALENO", "ALEOA",
    "ALEOT", "ALERA", "ALETA", "ALETO", "ALEVA", "ALFAI", "ALFAS", "ALFIL", "ALFIM", "ALFIR",
    "ALFOZ", "ALFUR", "ALGAL", "ALGAM", "ALGAR", "ALGAS", "ALGAZ", "ALGER", "ALGES", "ALGIA",
    "ALGOL", "ALGOS", "ALGOZ", "ALGUE", "ALGUM", "ALGUR", "ALHAL", "ALHAR", "ALHAS", "ALHEI",
    "ALHIA", "ALHOS", "ALIAM", "ALIAR", "ALIAS", "ALIBI", "ALICA", "ALICE", "ALICO", "ALIEI",
    "ALIEM", "ALIES", "ALIFA", "ALIFO", "ALIJA", "ALIJE", "ALIJO", "ALILA", "ALILO", "ALIME",
    "ALIMO", "ALINA", "ALINE", "ALIOU", "ALIPE", "ALIPO", "ALISA", "ALISE", "ALISO", "ALITA",
    "ALIVE", "ALJAR", "ALJAS", "ALJOZ", "ALJUR", "ALJUS", "ALMAS", "ALMEJ", "ALMES", "ALMEZ",
    "ALMIA", "ALMOA", "ALMOC", "ALMOM", "ALOES", "ALOGE", "ALOIS", "ALOJA", "ALOJE", "ALOJO",
    "ALONA", "ALONE", "ALOSE", "ALOTA", "ALOTE", "ALOTO", "ALPES", "ALQUE", "ALQUI", "ALSOL",
    "ALTAI", "ALTAR", "ALTAS", "ALTEA", "ALTEI", "ALTIA", "ALTIL", "ALTOR", "ALTOS", "ALUAR",
    "ALUAS", "ALUCO", "ALUDA", "ALUDE", "ALUDI", "ALUDO", "ALUFS", "ALUGA", "ALUGO", "ALUIA",
    "ALUIR", "ALUIU", "ALUJA", "ALUME", "ALUMO", "ALUNA", "ALUNO", "ALUOU", "ALURA", "ALVAI",
    "ALVAL", "ALVAR", "ALVAS", "ALVEA", "ALVEO", "ALVES", "ALVIM", "ALVIS", "ALVIT", "ALVOS",
    "ALVOR", "ALXIM", "AMACA", "AMACI", "AMACO", "AMADA", "AMADO", "AMADU", "AMAGA", "AMAGO",
    "AMAIN", "AMAIS", "AMALA", "AMALO", "AMAME", "AMANA", "AMAPA", "AMARA", "AMARE", "AMARO",
    "AMATA", "AMATE", "AMATO", "AMAVA", "AMBAR", "AMBAS", "AMBOS", "AMBRE", "AMBRO", "AMEAR",
    "AMEAS", "AMEBA", "AMECA", "AMEIA", "AMEIS", "AMEJU", "AMELA", "AMELO", "AMEMO", "AMENA",
    "AMENE", "AMENO", "AMEOU", "AMERE", "AMERO", "AMESA", "AMIAM", "AMIBO", "AMICA", "AMIDA",
    "AMIDO", "AMIEI", "AMIGA", "AMIGO", "AMILA", "AMILO", "AMIMA", "AMIME", "AMIMO", "AMINA",
    "AMINO", "AMIOS", "AMITE", "AMITO", "AMOJA", "AMOJE", "AMOJO", "AMOLA", "AMOLE", "AMOLO",
    "AMOMO", "AMORA", "AMORE", "AMORO", "AMOTA", "AMOVA", "AMOVE", "AMOVI", "AMOVO", "AMPAR",
    "AMPLA", "AMPLO", "AMUAM", "AMUAR", "AMUAS", "AMUCA", "AMUEI", "AMUEM", "AMUES", "AMUOS",
    "AMUOU", "AMURA", "AMURO", "AMUSA", "AMUSO", "ANAIS", "ANATA", "ANATO", "ANAUA", "ANBAB",
    "ANCAO", "ANCAR", "ANCAS", "ANCHO", "ANCIA", "ANCOS", "ANDAI", "ANDAM", "ANDAR", "ANDAS",
    "ANDEI", "ANDEM", "ANDES", "ANDIM", "ANDOA", "ANDOR", "ANDOU", "ANDRA", "ANDUA", "ANEAR",
    "ANEBO", "ANEDA", "ANEEL", "ANEGA", "ANEIA", "ANEIS", "ANEJO", "ANELA", "ANELE", "ANELO",
    "ANEMA", "ANEMO", "ANETE", "ANETO", "ANEXA", "ANEXE", "ANEXO", "ANFIO", "ANGAS", "ANGEL",
    "ANGLO", "ANGOR", "ANGRA", "ANGUL", "ANIBO", "ANIDO", "ANILA", "ANILE", "ANILH", "ANILO",
    "ANIMA", "ANIME", "ANIMO", "ANINA", "ANINE", "ANINO", "ANION", "ANITA", "ANITE", "ANITO",
    "ANJOS", "ANJOU", "ANKER", "ANODO", "ANOJA", "ANOJE", "ANOJO", "ANONA", "ANOPS", "ANORI",
    "ANORO", "ANOTA", "ANOTE", "ANOTO", "ANOUK", "ANSIA", "ANTAQ", "ANTAR", "ANTAS", "ANTES",
    "ANTEU", "ANTIA", "ANTIS", "ANTJO", "ANTRA", "ANTRE", "ANTRO", "ANUAL", "ANUAR", "ANUIA",
    "ANUIL", "ANUIR", "ANUIS", "ANUIU", "ANUJA", "ANULA", "ANULE", "ANULO", "ANURI", "ANURO",
    "AONDE", "AONIA", "AONIO", "AORTA", "APAGA", "APAGO", "APAIS", "APALA", "APALE", "APALO",
    "APAPA", "APARA", "APARE", "APARO", "APEAI", "APEAM", "APEAR", "APEAS", "APECE", "APEDA",
    "APEDE", "APEGA", "APEGO", "APEIA", "APEIE", "APEIO", "APEJA", "APELA", "APELE", "APELO",
    "APENA", "APENE", "APENO", "APEOC", "APEPI", "APERO", "APETI", "APEUA", "APIAS",
    "APICA", "APICE", "APICO", "APIEI", "APIEM", "APIES", "APINA", "APINE", "APINO", "APIOS",
    "APIPA", "APIPE", "APIPO", "APITA", "APITE", "APITO", "APLHA", "APNEA", "APOEI", "APOIA",
    "APOIE", "APOIO", "APOJO", "APOLA", "APOLE", "APOLO", "APOMO", "APONA", "APONE", "APONO",
    "APOOU", "APOTA", "APODE", "APODO", "APPEL", "APPLE", "APRAZ", "APREA", "APROA", "APROE",
    "APROO", "APTAM", "APTAR", "APTAS", "APTEI", "APTEM", "APTES", "APTOS", "APTOU", "APUPA",
    "APUPE", "APUPO", "APURA", "APURE", "APURO", "AQUEM", "AQUEU", "ARABA", "ARABE", "ARABI",
    "ARABO", "ARACA", "ARACU", "ARADA", "ARADO", "ARAFE", "ARAIS", "ARAIU", "ARALE", "ARAMA",
    "ARAME", "ARANA", "ARARA", "ARARI", "ARATU", "ARAUA", "ARAUE", "ARAVA", "ARAXA", "ARBIM",
    "ARCAO", "ARCAR", "ARCAS", "ARCAZ", "ARCHA", "ARCOS", "ARCOU", "ARDEA", "ARDEM", "ARDER",
    "ARDEU", "ARDIA", "ARDIL", "ARDIS", "ARDOR", "ARDRA", "ARDUA", "ARDUO", "AREAL", "AREAO",
    "AREAR", "AREAS", "ARECA", "AREDE", "AREIA", "AREJA", "AREJO", "ARENA", "AREOU", "AREPA",
    "ARERE", "ARFAR", "ARFIL", "ARGAO", "ARGAS", "ARGAU", "ARGEL", "ARGOL", "ARGOS", "ARGOT",
    "ARGUI", "ARGUM", "ARGUO", "ARIAS", "ARIBE", "ARICA", "ARICO", "ARIDA", "ARIDO", "ARIES",
    "ARIGO", "ARILA", "ARILO", "ARIMA", "ARINA", "ARION", "ARIPA", "ARIPO", "ARIRI", "ARITA",
    "ARLES", "ARMAM", "ARMAO", "ARMAR", "ARMAS", "ARMAU", "ARMCO", "ARMEI", "ARMEM", "ARMEU",
    "ARMIM", "ARMOU", "ARMUR", "ARNES", "ARNON", "AROCA", "AROMA", "ARPAO", "ARPAR", "ARPEU",
    "ARPOA", "ARQUE", "ARRAS", "ARRES", "ARRIO", "ARROZ", "ARRUA", "ARSES", "ARSIS", "ARTES",
    "ARTIS", "ARTUR", "ARUAI", "ARUBA", "ARUBE", "ARUCA", "ARUGA", "ARUJA", "ARULA", "ARUMA",
    "ARUPA", "ARURA", "ARURU", "ARVAL", "ASADO", "ASANA", "ASAPH", "ASARO", "ASCIA", "ASCII",
    "ASCIO", "ASCON", "ASCOS", "ASCUA", "ASIDO", "ASILO", "ASNAL", "ASNAR", "ASNAS", "ASNIL",
    "ASNOS", "ASPAR", "ASPAS", "ASPOU", "ASSAI", "ASSAM", "ASSAR", "ASSAZ", "ASSES", "ASSIM",
    "ASSIS", "ASSOA", "ASSOU", "ASSUA", "ASTER", "ASTRO", "ATACA", "ATADA", "ATADO", "ATAGA",
    "ATANA", "ATAPU", "ATARE", "ATAVA", "ATEAR", "ATEIA", "ATEIE", "ATELA", "ATELE", "ATENA",
    "ATEOU", "ATEUS", "ATEVE", "ATICA", "ATICO", "ATICU", "ATILA", "ATIMO", "ATINO", "ATIRA",
    "ATIRO", "ATITO", "ATIVA", "ATIVO", "ATLAS", "ATLED", "ATOAR", "ATOBA", "ATOCO", "ATOIS",
    "ATOLA", "ATOMO", "ATONA", "ATONO", "ATORA", "ATOTO", "ATRAI", "ATRAS", "ATRIL", "ATRIO",
    "ATRIZ", "ATROA", "ATROO", "ATROZ", "ATUAL", "ATUAM", "ATUAR", "ATUEM", "ATUMA", "ATUNS",
    "ATUOU", "ATURA", "ATXIM", "AUACU", "AUAIU", "AUARI", "AUATI", "AUDAZ", "AUDIO", "AUETI",
    "AUGER", "AUGIR", "AUIBA", "AULAS", "AULIA", "AULIR", "AULOS", "AUNAR", "AURAL", "AURAS",
    "AUREA", "AUREO", "AUSTE", "AUTOR", "AUTOS", "AUUVA", "AVAIS", "AVARA", "AVARO", "AVATI",
    "AVEAL", "AVEIA", "AVEIO", "AVELA", "AVENA", "AVEZO", "AVIAO", "AVIAR", "AVIDA", "AVIDE",
    "AVIDO", "AVILA", "AVIOS", "AVIOU", "AVISA", "AVISO", "AVITO", "AVIVA", "AVOAR", "AVOCA",
    "AXEXE", "AXIAL", "AXILA", "AXILO", "AXITE", "AXIXA", "AXONE", "AXOXO", "AXUPE", "AZADO",
    "AZALA", "AZEDA", "AZEDO", "AZEIA", "AZERI", "AZEVA", "AZIDA", "AZIGO", "AZIMO", "AZINA",
    "AZOAR", "AZOIS", "AZOLA", "AZOOU", "AZOTO", "AZOXI", "AZUIS", "AZULA", "BOLEM", "BOLHA",
    "BOLIM", "BOLIR", "BOLOR", "BOLOS", "BOLSA", "BOLSO", "BOMBA", "BOMBO", "BONDE", "BONDS",
    "BONES", "BONGO", "BONUS", "BONZA", "BONZO", "BOOKS", "BOOLE", "BOOMS", "BOQUE", "BORAL",
    "BORAX", "BORBA", "BORCO", "BORDA", "BORDO", "BORGO", "BORIS", "BORJA", "BORLA", "BORNE",
    "BORNO", "BOROA", "BORRA", "BORRO", "BOSCA", "BOSCO", "BOSON", "BOSSA", "BOSTA", "BOTAM",
    "BOTAO", "BOTAR", "BOTAS", "BOTEI", "BOTEM", "BOTES", "BOTIM", "BOTON", "BOTOS", "BOTOU",
    "BOTOX", "BOUBA", "BOXAR", "BOXER", "BOXES", "BRABA", "BRABO", "BRACA", "BRACO", "BRADA",
    "BRADO", "BRAGA", "BRAGG", "BRALA", "BRAMA", "BRAME", "BRAMI", "BRASA", "BRAVA", "BRAVO",
    "BREAK", "BREAR", "BRECA", "BREDO", "BREGA", "BREIA", "BREJA", "BREJO", "BREMA", "BREOU",
    "BRETA", "BRETE", "BREVE", "BRIAL", "BRIBA", "BRICA", "BRIDA", "BRIGA", "BRIOL", "BRIOS",
    "BRIOT", "BRISA", "BRITA", "BRITO", "BRIZA", "BROAS", "BROCA", "BROCO", "BROMA", "BROMO",
    "BROTA", "BROTE", "BROTO", "BROWN", "BROXA", "BRUAA", "BRUCO", "BRUEU", "BRUMA", "BRUNE",
    "BRUNI", "BRUNO", "BRUTA", "BRUTO", "BRUXA", "BRUXO", "BUAVA", "BUBAO", "BUCAL", "BUCAS",
    "BUCHA", "BUCHO", "BUCIM", "BUCLE", "BUCRE", "BUCUI", "BUDAS", "BUENA", "BUENO", "BUFAO",
    "BUFAR", "BUFAS", "BUFIR", "BUFOS", "BUGGY", "BUGIA", "BUGIO", "BUGLE", "BUGRA", "BUGRE",
    "BUIDO", "BUJAO", "BULAM", "BULAR", "BULAS", "BULBO", "BULHA", "BULIA", "BULIR", "BULIU",
    "BUMBA", "BUMBO", "BUNDA", "BUNDO", "BUQUE", "BURCA", "BURDO", "BUREL", "BURGO", "BURIL",
    "BURIS", "BURKE", "BURLA", "BURNU", "BURRA", "BURRO", "BURSA", "BUSAN", "BUSAO", "BUSCA",
    "BUSCO", "BUSES", "BUSTO", "BUTAO", "BUTEO", "BUTES", "BUTIA", "BUTIM", "BUTIO", "BUTRE",
    "BUTUA", "BUVAR", "BUXAL", "BUXOS", "BUZIA", "BUZIO", "BUZOS", "BYRON", "BYTES", "CABAL",
    "CABER", "CABOS", "CABRA", "CACAU", "CAIXA", "CALDO", "CALHA", "CALMA", "CALMO", "CALOR",
    "CALVA", "CALVO", "CAMPA", "CAMPO", "CANAL", "CANCE", "CANIL", "CANJA", "CANOA", "CANSO",
    "CANTE", "CANTO", "CANZO", "CAPAZ", "CAPUZ", "CARDA", "CARGA", "CARMA", "CARNE", "CARGO",
    "CARRO", "CARTA", "CASAL", "CASAR", "CASCA", "CASCO", "CASTA", "CASTO", "CATRE", "CAUDA",
    "CAULE", "CAUSA", "CAUSO", "CAVOS", "CEDER", "CEGAS", "CEIFA", "CEITA", "CEIAS", "CEIFO",
    "CENAS", "CENHO", "CENSO", "CENTO", "CERCA", "CERCO", "CERNE", "CERNI", "CERTO", "CESTA",
    "CETIM", "CETRO", "CHAGA", "CHALE", "CHAMA", "CHAPA", "CHATA", "CHATO", "CHAVE", "CHEFE",
    "CHEIA", "CHEIO", "CHEIRO", "CHIAS", "CHINA", "CHORO", "CHOCA", "CHULA", "CHULO", "CHUMBO",
    "CHUTE", "CHUVA", "CICLO", "CIDRA", "CIFRA", "CINDA", "CINTO", "CINZA", "CIOSO", "CIRCO",
    "CISAO", "CISMA", "CITAR", "CIVEL", "CIVIL", "CIUME", "CLAME", "CLARA", "CLARO", "CLASSE",
    "CLAVA", "CLEAN", "CLERO", "CLIMA", "CLINA", "CLOSE", "CLUBE", "COAVA", "COBRA", "COBRE",
    "COCA", "COCAR", "COCHO", "COELHO", "COESO", "COEVA", "COEVO", "COFRE", "COIBA", "COIFA",
    "COISA", "COITE", "COITO", "COLAR", "COMER", "COMIA", "COMBO", "COMUM", "CONDE", "CONTE",
    "CONTO", "CONVEM", "COPAS", "COPIA", "COPOS", "CORAG", "CORAL", "CORAR", "CORDA", "CORJA",
    "COROA", "CORPO", "CORSO", "CORTE", "CORVO", "COSER", "COSMO", "COSTA", "COURO", "COUSA",
    "COVEM", "COVER", "COVIL", "COXA", "COZER", "CRASE", "CRAVO", "CREDO", "CREEM", "CREME",
    "CRIAR", "CRIAS", "CRICA", "CRIEI", "CRIEM", "CRILA", "CRIME", "CRINA", "CRINO", "CRIOU",
    "CRISE", "CRISO", "CRIVA", "CRIVO", "CROCA", "CROCO", "CROMA", "CROMO", "CROSS", "CROTA",
    "CRUAS", "CRUCA", "CRUEL", "CRUME", "CRUOR", "CRUPE", "CRUZA", "CRUZO", "CUATA", "CUBAR",
    "CUBAS", "CUBEO", "CUBIO", "CUBIU", "CUBOS", "CUCAR", "CUCHE", "CUCOS", "CUECA", "CUERA",
    "CUFEA", "CUFIA", "CUIAS", "CUICA", "CUIDA", "CUIDE", "CUIDO", "CUIRA", "CUITA", "CUITE",
    "CUJAS", "CUJOS", "CULPA", "CULPO", "CULTA", "CULTO", "CUMAI", "CUMBA", "CUMBE", "CUMEL",
    "CUMES", "CUMIM", "CUMIS", "CUNAU", "CUNCA", "CUNEO", "CUNHA", "CUNHO", "CUPAI", "CUPAO",
    "CUPIM", "CUPOM", "CUQUE", "CURAM", "CURAR", "CURAS", "CURAU", "CURDO", "CURIA", "CURIE",
    "CURIO", "CUROU", "CURRA", "CURRO", "CURRY", "CURSA", "CURSO", "CURTA", "CURTE", "CURTI",
    "CURTO", "CURUA", "CURUL", "CURVA", "CURVO", "CUSCO", "CUSPA", "CUSPE", "CUSPO", "CUSSO",
    "CUSTA", "CUSTE", "CUSTO", "CUTER", "CUTIA", "CUTIS", "CUXIU", "DACAO", "DACAR", "DACCA",
    "DACIA", "DACIO", "DACMA", "DADAS", "DADOR", "DADOS", "DAFNE", "DAIME", "DAIRO", "DAKAR",
    "DAKIN", "DALEM", "DALIA", "DALVA", "DAMAS", "DAMBA", "DAMOS", "DANAO", "DANAR", "DANCA",
    "DANDI", "DANDO", "DANES", "DANIO", "DANOS", "DANOU", "DANTE", "DAOME", "DAQUI", "DARAF",
    "DARAO", "DARBY", "DARCY", "DARDO", "DAREI", "DAREM", "DARGA", "DARIA", "DARIO", "DARIS",
    "DARMA", "DARTO", "DASIA", "DATAL", "DATAM", "DATAR", "DATAS", "DATIL", "DATOU", "DATUM",
    "DAUCO", "DAVAM", "DAVID", "DEADO", "DEBAR", "DEBIL", "DECAI", "DECAO", "DECHO", "DECIL",
    "DECIS", "DECOR", "DEDAL", "DEDAO", "DEDAR", "DEDOS", "DEDUZ", "DEGAS", "DEITA", "DEITO",
    "DEIXA", "DEIXE", "DEIXO", "DEJUA", "DELAS", "DELES", "DELFO", "DELHI", "DELIA", "DELIO",
    "DELIR", "DELIU", "DELLA", "DELOS", "DELTA", "DEMAO", "DEMOS", "DENDE", "DENDI", "DENGO",
    "DENIS", "DENSA", "DENSO", "DENTE", "DEPOE", "DEPOR", "DEPOS", "DEPRE", "DEPUS", "DEQUE",
    "DERAM", "DERBI", "DERMA", "DERME", "DESAR", "DESCA", "DESCE", "DESCI", "DESCO", "DESDA",
    "DESDE", "DESMA", "DESNU", "DESPE", "DESSA", "DESSE", "DESTA", "DESTE", "DETEM", "DETER",
    "DEUSA", "DEVAM", "DEVAS", "DEVEM", "DEVER", "DEVES", "DEVIA", "DEVIO", "DEVIR", "DEWEY",
    "DHAKA", "DIABA", "DIABO", "DIADA", "DIADE", "DIALE", "DIANA", "DIAZO", "DICAO", "DICAR",
    "DICAS", "DICAZ", "DICHA", "DIDOT", "DIECO", "DIEGO", "DIENO", "DIESE", "DIETA", "DIGAM",
    "DIGAS", "DIGNA", "DIGNE", "DIGNO", "DILUI", "DINAR", "DINDA", "DINDO", "DINGA", "DINGO",
    "DINIS", "DIODO", "DIOGO", "DIOPA", "DIOPE", "DIORE", "DIOSO", "DIPLE", "DIPLO", "DIQUE",
    "DIRAC", "DIRCA", "DIREI", "DIREM", "DIRIA", "DIRRA", "DISCO", "DISEL", "DISGA", "DISSE",
    "DISSO", "DISTA", "DISTO", "DITAM", "DITAR", "DITAS", "DITOS", "DITOU", "DIULA", "DIVAS",
    "DIXIS", "DIZEL", "DIZEM", "DIZER", "DIZES", "DIZIA", "DOADA", "DOADO", "DOBAM", "DOBAR",
    "DOBLA", "DOBLE", "DOBOU", "DOBRA", "DOBRE", "DOBRO", "DOCAR", "DOCAS", "DOCES", "DOCIL",
    "DOCTO", "DODOI", "DOGAL", "DOGAO", "DOGMA", "DOGON", "DOGUE", "DOIAM", "DOIDA", "DOIDO",
    "DOLAR", "DOLBY", "DOLCE", "DOLLY", "DOLMA", "DOMAR", "DOMOU", "DONAS", "DONDE", "DONOS",
    "DOPAR", "DORAS", "DORES", "DORIO", "DORIS", "DORME", "DORMI", "DORNA", "DORSO", "DOSAM",
    "DOSAR", "DOSES", "DOSOU", "DOTAL", "DOTAR", "DOTES", "DOTIM", "DOTOU", "DOUDA", "DOUDO",
    "DOULA", "DOURA", "DOURO", "DOUTA", "DOUTO", "DOZES", "DRACO", "DRAGA", "DRAGO", "DRAMA",
    "DRAPE", "DREAD", "DRENA", "DRENO", "DRIAS", "DRICA", "DRILO", "DRINK", "DRIVE", "DROGA",
    "DROMO", "DRONE", "DROPE", "DROPS", "DRUPA", "DRUSA", "DRUSO", "DRUVA", "DUALA", "DUBAI",
    "DUBIA", "DUBIO", "DUBLA", "DUBLE", "DUCAL", "DUCHA", "DUCTO", "DUELO", "DUERE", "DUETO",
    "DUGAO", "DULCE", "DULIA", "DUMAS", "DUNAS", "DUNDU", "DUNGA", "DUPLA", "DUPLO", "DUQUE",
    "DURAL", "DURAM", "DURAO", "DURAR", "DURAS", "DURAZ", "DUREX", "DURIO", "DURMO", "DUROL",
    "DUROS", "DUROU", "DURRA", "DUTOS", "DUTRA", "DUTRO", "DUVIA", "DUZIA", "DZETA", "EAGLE",
    "EBAME", "EBANO", "EBIRI", "EBOME", "EBRIO", "EBULO", "ECESE", "ECLER", "ECLES", "ECOAM",
    "ECOAR", "ECOOU", "ECRAN", "ECURU", "EDACE", "EDEIA", "EDEMA", "EDERE", "EDGAR", "EDIPO",
    "EDITA", "EDITO", "EDUCA", "EDULE", "EDULO", "EDWIN", "EFEBO", "EFESO", "EFETA", "EFLUI",
    "EFODE", "EFORO", "EFUSO", "EGBAS", "EGIDE", "EGIPA", "EGITO", "EGRIO", "EGUAR", "EGUAS",
    "EGUNS", "EIDER", "EIRAS", "EIVAR", "EIVOU", "EIXAR", "EIXOS", "EJETA", "EJETO", "EKBOM",
    "ELATE", "ELCHE", "ELEDA", "ELEDE", "ELEGE", "ELEIA", "ELEMI", "ELENA", "ELEPE", "ELEVA",
    "ELIAS", "ELIDA", "ELIDE", "ELIOT", "ELISA", "ELITE", "ELMOS", "ELUIR", "ELURO", "ELVIS",
    "EMANA", "EMBEU", "EMBIA", "EMBIU", "EMBUA", "EMBUI", "EMBUU", "EMEIO", "EMELE", "EMERO",
    "EMESE", "EMICO", "EMILE", "EMITA", "EMITE", "EMOTO", "EMPAR", "EMPAS", "EMPOS", "EMULA",
    "EMULO", "ENASE", "ENCHA", "ENCHE", "ENCKE", "ENDEZ", "ENDOR", "ENDRO", "ENEMA", "ENFIA",
    "ENFIM", "ENGAR", "ENGOS", "ENGRA", "ENIAC", "ENITO", "ENJOA", "ENJOO", "ENODO", "ENOJA",
    "ENOJO", "ENORA", "ENQUE", "ENTAO", "ENTAS", "ENTER", "ENTES", "ENTEU", "ENTOA", "ENTRA",
    "ENTRE", "ENTRO", "ENULA", "ENVES", "ENVIA", "ENVIO", "ENXOS", "ENXUI", "EOIPO", "EOLIA",
    "EOLIO", "EONES", "EPICA", "EPICO", "EPIRO", "EPOCA", "EPODO", "EPOXI", "EPSOM", "EPSON",
    "EPURA", "EPUXA", "EQUIO", "ERADO", "ERAMA", "ERATO", "ERBIA", "ERBIO", "EREBO", "EREMA",
    "ERERE", "ERETA", "ERETO", "ERGAM", "ERGIO", "ERGOL", "ERGUE", "ERICA", "ERICE", "ERICO",
    "ERIGE", "ERINA", "ERMAR", "ERMOS", "ERMOU", "ERNST", "EROSO", "ERRAM", "ERRAR", "ERREI",
    "ERRES", "ERROR", "ERROS", "ERROU", "ERUCA", "ERVAL", "ERVAO", "ERVAR", "ERVAS", "ESCOA",
    "ESCOL", "ESERE", "ESGAR", "ESMAR", "ESMOI", "ESOPO", "ESPIA", "ESPIR", "ESPRU", "ESQUI",
    "ESSAS", "ESSES", "ESTAI", "ESTAO", "ESTAR", "ESTAS", "ESTAT", "ESTAU", "ESTER", "ESTES",
    "ESTIA", "ESTIO", "ESTOL", "ESTOU", "ESTRO", "ESTUA", "ESULA", "ESVAI", "ESVAO", "ETANO",
    "ETAPA", "ETENO", "ETHOS", "ETICA", "ETICO", "ETILA", "ETILO", "ETIMO", "ETINO", "ETNIA",
    "EUDES", "EULER", "EUROS", "EVASE", "EVITA", "EVITE", "EVOCA", "EVOLA", "EVORA", "EXALA",
    "EXALE", "EXAME", "EXATA", "EXATO", "EXIBE", "EXIGE", "EXIJA", "EXILE", "EXIME", "EXINA",
    "EXITO", "EXODO", "EXONS", "EXPIA", "EXPOE", "EXPOR", "EXPOS", "EXTRA", "EXULE", "FABIO",
    "FABRA", "FABRO", "FACAM", "FACAO", "FACAS", "FACAS", "FACES", "FACHA", "FACHO", "FACIL",
    "FADAR", "FADAS", "FADOS", "FADOU", "FAIAL", "FAIAR", "FAIAS", "FAINA", "FAIXA", "FALAM",
    "FALAR", "FALAS", "FALAZ", "FALCA", "FALDA", "FALEI", "FALEM", "FALES", "FALHA", "FALHE",
    "FALHO", "FALIR", "FALIU", "FALOU", "FALSA", "FALSO", "FALTA", "FALTE", "FALTO", "FALUA",
    "FALUM", "FALUS", "FANAL", "FANAR", "FANCA", "FANDO", "FANFA", "FANGA", "FANHO", "FANTI",
    "FAQUI", "FARAD", "FARAO", "FARAS", "FARDA", "FARDO", "FAREI", "FARIA", "FARNE", "FARNO",
    "FAROL", "FARPA", "FARRA", "FARRO", "FARSA", "FARSI", "FARTA", "FARTE", "FARTO", "FASCO",
    "FASES", "FASOR", "FASSO", "FASTO", "FATAL", "FATIA", "FATOR", "FATOS", "FATUO", "FAUCE",
    "FAULA", "FAUNA", "FAUNO", "FAVAL", "FAVAR", "FAVAS", "FAVOR", "FAVOS", "FAXES", "FAZEM",
    "FAZER", "FAZES", "FAZIA", "FEBEU", "FEBRA", "FEBRE", "FECAL", "FECHA", "FECHO", "FECIO",
    "FEDEM", "FEDER", "FEDEU", "FEDOR", "FEDRO", "FEIAS", "FEIJO", "FEILA", "FEIOS", "FEIRA",
    "FEITA", "FEITO", "FEIXE", "FELEO", "FELES", "FELGA", "FELIS", "FELIX", "FELIZ", "FELPA",
    "FELPO", "FEMEA", "FEMEO", "FEMUR", "FENAR", "FENDA", "FENDE", "FENIL", "FENIX", "FENOL",
    "FEOFO", "FERAL", "FERAS", "FERAZ", "FEREM", "FERIA", "FERIR", "FERIU", "FERMI", "FEROZ",
    "FERRA", "FERRO", "FERRY", "FERVE", "FERVO", "FESTA", "FESTO", "FETAL", "FETAO", "FETOS",
    "FEUDO", "FEZES", "FIADA", "FIADO", "FIAPO", "FIAVA", "FIBRA", "FICAM", "FICAO", "FICAS",
    "FICHA", "FICHU", "FICOU", "FICTO", "FICUS", "FIDEL", "FIDEU", "FIDJI", "FIEIS", "FIEZA",
    "FIFIA", "FIGAS", "FIGLE", "FIGOS", "FILAO", "FILAR", "FILAS", "FILER", "FILES", "FILHA",
    "FILHO", "FILHO", "FILIA", "FILMA", "FILME", "FILOS", "FILOU", "FIMAS", "FIMIA", "FINAL",
    "FINAR", "FINAS", "FINCA", "FINCO", "FINDA", "FINDO", "FINES", "FINFA", "FINGE", "FINGI",
    "FINOS", "FINOU", "FINTA", "FIOFO", "FIOLO", "FIOTA", "FIOTE", "FIOTO", "FIQUE", "FIRMA",
    "FIRME", "FIRMO", "FISCO", "FISGA", "FISGO", "FISIS", "FITAR", "FITAS", "FITIL", "FITOL",
    "FITOS", "FITOU", "FIUME", "FIUSA", "FIUZA", "FIUZO", "FIXAM", "FIXAR", "FIXAS", "FIXOS",
    "FIXOU", "FIZER", "FLACO", "FLAMA", "FLAME", "FLANA", "FLAPE", "FLAPS", "FLARE", "FLASH",
    "FLATO", "FLATS", "FLAVA", "FLAVO", "FLEME", "FLETE", "FLEXO", "FLOCO", "FLORA", "FLOSO",
    "FLOXO", "FLOZO", "FLUIA", "FLUIR", "FLUIU", "FLUME", "FLUOR", "FLUSH", "FLUXO", "FOBAR",
    "FOBIA", "FOBOS", "FOCAL", "FOCAR", "FOCAS", "FOCIO", "FOCOS", "FODAM", "FODER", "FODEU",
    "FODIA", "FOFAR", "FOFOS", "FOFOU", "FOGAO", "FOGEM", "FOGES", "FOGOS", "FOICE", "FOITO",
    "FOJOS", "FOLAR", "FOLES", "FOLGA", "FOLGO", "FOLHA", "FOLHO", "FOLIA", "FOLIO", "FOMES",
    "FOMOS", "FONES", "FONIA", "FONON", "FONTE", "FORAL", "FORAM", "FORCA", "FORCO", "FORDE",
    "FORDO", "FOREM", "FORES", "FORIA", "FORJA", "FORJE", "FORMA", "FORME", "FORMI", "FORMO",
    "FORNO", "FOROS", "FORRA", "FORRO", "FORTE", "FORUM", "FOSCA", "FOSCO", "FOSSA", "FOSSE",
    "FOSSO", "FOSTE", "FOTIO", "FOTON", "FOTOS", "FOUCE", "FOULS", "FOVEA", "GABAO", "GABAR",
    "GABOS", "GABOU", "GABRO", "GACHA", "GACHO", "GADAO", "GADAR", "GADES", "GADOS", "GAFAR",
    "GAFES", "GAGAU", "GAGOS", "GAGUE", "GAIAL", "GAIAS", "GAITA", "GAIVA", "GAJAO", "GAJOS",
    "GALAO", "GALAR", "GALAS", "GALBA", "GALBO", "GALEA", "GALES", "GALGA", "GALGO", "GALHA",
    "GALHO", "GALIA", "GALIO", "GALOS", "GALRA", "GAMAL", "GAMAO", "GAMAR", "GAMAS", "GAMBA",
    "GAMES", "GAMOU", "GANAS", "GANCA", "GANDU", "GANES", "GANGA", "GANHA", "GANHE", "GANHO",
    "GANIR", "GANJA", "GANSA", "GANSO", "GANZA", "GANZE", "GARBO", "GARCA", "GARCO", "GARFA",
    "GARFO", "GARIS", "GAROA", "GARRA", "GARRO", "GARUA", "GASES", "GASPA", "GASTA", "GASTE",
    "GASTO", "GATAO", "GATAS", "GATIL", "GATOS", "GATUM", "GAUDA", "GAUGE", "GAULO", "GAURO",
    "GAUSE", "GAUSS", "GAVAR", "GAVEA", "GAVIA", "GAZAL", "GAZAO", "GAZEL", "GAZEO", "GAZES",
    "GAZEU", "GAZIA", "GAZUA", "GEADA", "GEADO", "GEARO", "GEBAR", "GEENA", "GELAM", "GELAR",
    "GELBA", "GELHA", "GELOS", "GELOU", "GEMAR", "GEMAS", "GEMEA", "GEMEO", "GEMER", "GEMIA",
    "GENAL", "GENAS", "GENES", "GENIO", "GENOA", "GENRO", "GENTE", "GEODE", "GEODO", "GEOGR",
    "GEORG", "GEOSO", "GERAL", "GERAM", "GERAR", "GERBO", "GEREM", "GERIR", "GERIU", "GERME",
    "GEROU", "GESSA", "GESSO", "GESTA", "GESTO", "GIAUR", "GIBAO", "GIBAS", "GIBBS", "GIBIS",
    "GICLE", "GIGIA", "GILIA", "GIMBO", "GINGA", "GINGE", "GINGO", "GINJA", "GIPSO", "GIRAM",
    "GIRAO", "GIRAR", "GIREM", "GIRIA", "GIRIO", "GIROS", "GIROU", "GIRUA", "GIZAR", "GIZES",
    "GIZOU", "GLACE", "GLEBA", "GLENA", "GLIAL", "GLIAS", "GLIDE", "GLIFO", "GLOBO", "GLOMO",
    "GLOSA", "GLOTA", "GLOTE", "GLUMA", "GLUON", "GLUTE", "GNOMA", "GNOME", "GNOMO", "GNOSE",
    "GOALS", "GODOI", "GODOS", "GOELA", "GOETE", "GOFRA", "GOIAS", "GOITI", "GOIVA", "GOIVO",
    "GOLAN", "GOLAS", "GOLDA", "GOLES", "GOLFE", "GOLFO", "GOLGI", "GOLOS", "GOLPE", "GOMAL",
    "GOMAR", "GOMAS", "GOMBO", "GOMES", "GOMIA", "GOMIL", "GOMOS", "GONDA", "GONGA", "GONGO",
    "GONIO", "GONIS", "GONZO", "GOPAK", "GORAL", "GORAR", "GORDA", "GORDO", "GORJA", "GORNE",
    "GOROU", "GORRA", "GORRO", "GOSMA", "GOSTA", "GOSTE", "GOSTO", "GOTAS", "GOUDA", "GOZAM",
    "GOZAR", "GOZOS", "GRAAF", "GRAAL", "GRACA", "GRADA", "GRADE", "GRADO", "GRAFE", "GRAFO",
    "GRAMA", "GRANA", "GRANO", "GRAOS", "GRAPA", "GRATA", "GRATO", "GRAUS", "GRAVA", "GRAVE",
    "GRAXA", "GRAXO", "GRAYS", "GREDA", "GREDE", "GREGA", "GREGE", "GREGO", "GRELA", "GRELO",
    "GRENA", "GRETA", "GREVE", "GRIFA", "GRIFE", "GRIFO", "GRILO", "GRIMA", "GRIMM", "GRIOS",
    "GRIPE", "GRISE", "GRISO", "GRISU", "GRITA", "GRITO", "GROIR", "GROLO", "GROMA", "GROOM",
    "GROSA", "GROTA", "GROUS", "GRUDA", "GRUDE", "GRUIM", "GRUIR", "GRUJA", "GRUMO", "GRUNA",
    "GRUPO", "GRUTA", "GUACA", "GUACO", "GUACU", "GUADO", "GUAIA", "GUAIS", "GUAIU", "GUAJA",
    "GUAJU", "GUAMA", "GUANA", "GUANO", "GUAPE", "GUAPO", "GUAPO", "GUARA", "GUARE", "GUARU",
    "GUATO", "GUAXA", "GUAXE", "GUAXI", "GUAXO", "GUEBA", "GUEBO", "GUELI", "GUERI", "GUETA",
    "GUETE", "GUETO", "GUEXA", "GUIAM", "GUIAO", "GUIAR", "GUIAS", "GUIBA", "GUIDO", "GUIEI",
    "GUIGA", "GUIGO", "GUINA", "GUINE", "GUIOU", "GUIPA", "GUIRA", "GUISA", "GUITA", "GUIZO",
    "GULAR", "GUMES", "GUNGA", "GUNJI", "GURIA", "GURUS", "HABIL", "HACER", "HADJI", "HAIKU",
    "HAITI", "HALFE", "HALOS", "HALUX", "HALWA", "HANSA", "HAPAX", "HARAS", "HAREM", "HARPA",
    "HARTO", "HASHI", "HASTA", "HASTE", "HATCH", "HAUCA", "HAVAI", "HAVER", "HAVIA", "HAWID",
    "HEGEL", "HELAS", "HELIO", "HELIX", "HEMAL", "HENRI", "HENRY", "HEPAR", "HERAS", "HERDA",
    "HEREU", "HERIL", "HERMA", "HEROI", "HEROO", "HERPO", "HERTZ", "HETEU", "HEVEA", "HEXIL",
    "HIATO", "HIDRA", "HIENA", "HIFAS", "HIFEN", "HIGGS", "HIJAB", "HILAR", "HIMEN", "HINDI",
    "HINDU", "HINIR", "HINOS", "HIRAX", "HIRCO", "HIRTA", "HIRTO", "HIULA", "HOBBY", "HOLCO",
    "HOMAO", "HOMEM", "HOMME", "HOMOS", "HOMUS", "HONOR", "HONRA", "HOOKE", "HOPAK", "HORAL",
    "HORAR", "HORAS", "HORDA", "HORTA", "HORTO", "HOSCO", "HOSTE", "HOTEL", "HOUSE", "HOUVE",
    "HULHA", "HUMBE", "HUMIL", "HUMOR", "HUMUS", "HUNOS", "HURON", "HURRA", "HUSKY", "HUTUS",
    "IACRI", "IAGUA", "IAMBO", "IANAN", "IANSA", "IAQUE", "IATAI", "IATES", "IBARO", "IBATE",
    "IBEJI", "IBERO", "IBIAI", "IBICE", "IBIRA", "IBIRI", "IBIRO", "IBOPE", "IBSEN", "ICACO",
    "ICADA", "ICADO", "ICANA", "ICARA", "ICARO", "ICATU", "ICICA", "ICIPO", "ICONE", "ICTUS",
    "IDADE", "IDEAL", "IDEAR", "IDEIA", "IDOLO", "IDOSA", "IDOSO", "IEITO", "IELMO", "IEMEN",
    "IGACI", "IGAPO", "IGARA", "IGBIM", "IGLUS", "IGNEA", "IGNEO", "IGUAI", "IGUAL", "IGUPA",
    "IIABA", "IJACI", "IJEBU", "IJEXA", "ILESA", "ILESO", "ILHAL", "ILHAR", "ILHAS", "ILHEU",
    "ILHOA", "ILHOS", "ILHOU", "ILICA", "ILICE", "ILION", "ILUDE", "ILUDI", "ILUSO", "IMAGO",
    "IMALA", "IMAME", "IMAMO", "IMANE", "IMANO", "IMBUS", "IMENE", "IMIDA", "IMIGO", "IMINA",
    "IMITA", "IMITE", "IMOLA", "IMOTO", "IMPAR", "IMPER", "IMPIO", "IMPOE", "IMPOR", "IMPOS",
    "IMUNE", "INAIA", "INAJA", "INAJE", "INALA", "INAMU", "INANA", "INANE", "INATA", "INATO",
    "INCAR", "INCAS", "INCHA", "INCOA", "INCOE", "INDEX", "INDEZ", "INDIA", "INDIO", "INDOL",
    "INDRI", "INDUZ", "INERE", "INFLA", "INFRA", "INGAI", "INGAS", "INGUA", "INIBE", "INION",
    "INOVA", "INPUT", "INSTA", "INSUA", "INTER", "INTUI", "INUBE", "INUBO", "INULA", "INVAR",
    "INVES", "INVIO", "IODAR", "IODOL", "IOGUE", "IONIO", "IONTE", "IOSIF", "IPADU", "IPECA",
    "IPECU", "IPERO", "IPETE", "IPIAU", "IPIRA", "IPORA", "IPPON", "IPRES", "IPUBI", "IPUCA",
    "IRADO", "IRANI", "IRARA", "IRATI", "IRECE", "IRENA", "IRERE", "IRIAL", "IRIAM", "IRIAR",
    "IRINA", "IRIRI", "IRISA", "IRITE", "IRMAO", "IRMAS", "IRMOS", "IROCO", "IROSO", "IRREG",
    "IRUCU", "IRUPI", "IRUSI", "ISAAC", "ISATE", "ISCAR", "ISCAS", "ISCOU", "ISLAO", "ISOLA",
    "ISSEI", "ISSEL", "ISTMO", "ITABI", "ITAJA", "ITAJI", "ITAJU", "ITALO", "ITAPU", "ITAUA",
    "ITENS", "ITRIA", "ITRIO", "ITUXI", "IUANE", "IUCAS", "IUDJA", "IURIS", "IVATE", "IVETE",
    "IVONE", "IVORA", "IVOTI", "IXORA", "IZMIR", "JABES", "JABRE", "JACAS", "JACOB", "JACTO",
    "JACUI", "JACUS", "JADER", "JAFET", "JAICO", "JAIME", "JAKOB", "JALAO", "JALDE", "JALES",
    "JALNE", "JAMBA", "JAMBE", "JAMBO", "JAMBU", "JAMES", "JANAU", "JANGO", "JANIO", "JANTA",
    "JANTE", "JAPAO", "JAPII", "JAPIM", "JAPOA", "JAPUE", "JAPUI", "JAQUE", "JARAS", "JARDA",
    "JARRA", "JARRO", "JARUS", "JASAO", "JASPE", "JATAI", "JATAR", "JATEI", "JATOR", "JATOS",
    "JAULA", "JAURU", "JAVAE", "JAVRE", "JAZEM", "JAZER", "JAZIA", "JEANS", "JEGUE", "JEIRA",
    "JEITO", "JEJES", "JEJUA", "JEJUM", "JEMBE", "JEOVA", "JEPUE", "JEQUE", "JEQUI", "JERRA",
    "JERZY", "JESUS", "JETAI", "JETOM", "JETON", "JICUI", "JIDDU", "JIHAD", "JIMBO", "JIMMY",
    "JINGA", "JINGO", "JIPAO", "JIPIO", "JIQUE", "JIQUI", "JIRAU", "JITAI", "JOANA", "JOANE",
    "JOBIM", "JOCAL", "JOGAM", "JOGAO", "JOGAR", "JOGOS", "JOGOU", "JOGUE", "JOHNE", "JOIAS",
    "JOLIZ", "JOLLY", "JONAS", "JONGO", "JONIA", "JONIO", "JORGE", "JORNA", "JORRA", "JORRO",
    "JOSEF", "JOSIP", "JOSUE", "JOTAS", "JOULE", "JOVEM", "JUATI", "JUBAI", "JUDAS", "JUDEU",
    "JUDIA", "JUGAL", "JUGAR", "JUINA", "JUIZA", "JUIZO", "JULES", "JULGA", "JULGO", "JULHO",
    "JULIA", "JULIO", "JUMAS", "JUNCA", "JUNCO", "JUNDU", "JUNGE", "JUNHO", "JUNIO", "JUNTA",
    "JUNTO", "JUPIA", "JURAO", "JURAR", "JURAS", "JURIS", "JUROS", "JUROU", "JURUA", "JUSTA",
    "JUSTE", "JUSTO", "JUTAI", "JUTOS", "JUUNA", "KAFKA", "KAMBA", "KANJI", "KARIN", "KARMA",
    "KEBAB", "KEITA", "KHMER", "KLEIN", "KOMBI", "KRAFT", "KRAHO", "KREBS", "KREYE", "KRILL",
    "KYRIE", "LABAO", "LABEU", "LABIA", "LABIL", "LABIO", "LABOR", "LABRO", "LACAN", "LACAO",
    "LACAR", "LACAS", "LACHA", "LACIO", "LACOS", "LACRA", "LACRE", "LADAO", "LADOS", "LADRA",
    "LADRO", "LAGAO", "LAGAR", "LAGOA", "LAGOS", "LAICA", "LAICH", "LAICO", "LAIDO", "LAILA",
    "LAITU", "LAIVO", "LAJAO", "LAJEA", "LAJEM", "LAJES", "LALAU", "LAMAS", "LAMBA", "LAMBE",
    "LAMBI", "LAMBU", "LAMER", "LAMIA", "LAMIO", "LAMPA", "LAMPO", "LANAR", "LANCA", "LANCE",
    "LANCO", "LANDA", "LANDE", "LANDI", "LANDO", "LANDU", "LANGE", "LANHO", "LANJA", "LANKA",
    "LANTI", "LAPAO", "LAPAS", "LAPIM", "LAPIS", "LAPSO", "LAPUZ", "LAQUE", "LARDO", "LARES",
    "LARGA", "LARGO", "LARIX", "LAROZ", "LARVA", "LASCA", "LASCO", "LASER", "LASSO", "LATAO",
    "LATAS", "LATEA", "LATEO", "LATER", "LATEX", "LATIA", "LATIM", "LATIR", "LATIU", "LAUDA",
    "LAUDE", "LAUDO", "LAURA", "LAURO", "LAUTA", "LAUTO", "LAUZA", "LAVAL", "LAVAM", "LAVAR",
    "LAVAS", "LAVEI", "LAVOR", "LAVOU", "LAVRA", "LAXAR", "LAZAO", "LAZAR", "LAZER", "LEAIS",
    "LEBRE", "LECRE", "LEDOR", "LEGAL", "LEGAR", "LEGOU", "LEGRA", "LEGRE", "LEGUA", "LEIGA",
    "LEIGH", "LEIGO", "LEIRA", "LEITA", "LEITE", "LEITO", "LEIVA", "LELEU", "LELIA", "LEMAN",
    "LEMBA", "LEMES", "LEMNA", "LEMOS", "LEMPA", "LEMUR", "LENCO", "LENDA", "LENDO", "LENEO",
    "LENEU", "LENHA", "LENHO", "LENIN", "LENIR", "LENOA", "LENTA", "LENTE", "LENTO", "LEOBA",
    "LEOES", "LEONE", "LEPAS", "LEPRA", "LEQUE", "LERAM", "LERAO", "LERCA", "LERDA", "LERDO",
    "LERIA", "LERNA", "LESAO", "LESAR", "LESIM", "LESMA", "LESOU", "LESSE", "LESTE", "LESTO",
    "LETAL", "LETAO", "LETES", "LETEU", "LETRA", "LEVAM", "LEVAR", "LEVEI", "LEVEM", "LEVES",
    "LEVEZ", "LEVOU", "LEXIA", "LEXIS", "LHAMA", "LHANO", "LHASA", "LIABO", "LIACA", "LIAME",
    "LIANA", "LIBAR", "LIBER", "LIBIA", "LIBIO", "LIBRA", "LIBRE", "LICAO", "LICAS", "LICEU",
    "LICHI", "LICIO", "LICOR", "LICOS", "LIDAR", "LIDAS", "LIDER", "LIDES", "LIDIA", "LIDOS",
    "LIDOU", "LIGAL", "LIGAM", "LIGAR", "LIGAS", "LIGEO", "LIGHT", "LIGIO", "LIGOU", "LIGUE",
    "LILAS", "LILIO", "LIMAO", "LIMAR", "LIMBO", "LIMOS", "LIMOU", "LIMPA", "LIMPO", "LINCE",
    "LINDA", "LINDE", "LINDO", "LINEO", "LINEU", "LINFA", "LINGA", "LINHA", "LINHO", "LINNE",
    "LIONS", "LIRIO", "LISAS", "LISIA", "LISIM", "LISIO", "LISLE", "LISOL", "LISOS", "LISSA",
    "LISTA", "LISZT", "LITAO", "LITEM", "LITIA", "LITIO", "LITOR", "LITRO", "LITUO", "LIVEL",
    "LIVIA", "LIVOR", "LIVRA", "LIVRE", "LIVRO", "LIXAO", "LIXAR", "LIXAS", "LIXOU", "LIZAR",
    "LOASA", "LOBAL", "LOBAO", "LOBAR", "LOBAZ", "LOBBY", "LOBOS", "LOCAL", "LOCAO", "LOCAR",
    "LOCRO", "LOCUS", "LODAO", "LOESS", "LOFIO", "LOFTS", "LOGAR", "LOGOS", "LOGOS", "LOGRA",
    "LOGRO", "LOICA", "LOIOS", "LOIRA", "LOIRE", "LOIRO", "LOISA", "LOITA", "LOJAS", "LOJIA",
    "LOLIO", "LOMAS", "LOMBA", "LOMBO", "LONAS", "LONCA", "LONDU", "LONGA", "LONGA", "LONGE",
    "LONGO", "LOOKS", "LOOPS", "LOPES", "LOQUE", "LORAN", "LORDE", "LORDS", "LORIS", "LOROS",
    "LORPA", "LORTO", "LOSNA", "LOTAR", "LOTES", "LOTOU", "LOTUS", "LOUCA", "LOUCO", "LOUIS",
    "LOURA", "LOURE", "LOURO", "LOUSA", "LOUSA", "LOUVA", "LOWEN", "LUADO", "LUANA", "LUCAS",
    "LUCIA", "LUCIO", "LUCRA", "LUCRO", "LUDAR", "LUDIO", "LUDRO", "LUFAR", "LUGAR", "LUGRE",
    "LUIGI", "LUISA", "LUITA", "LULAS", "LUMEN", "LUMES", "LUNAR", "LUNDA", "LUNDU", "LUNFA",
    "LUNGA", "LUNGE", "LUPAR", "LUPIA", "LUPUS", "LURAR", "LURAS", "LURIA", "LUSCO", "LUSOS",
    "LUTAM", "LUTAR", "LUTAS", "LUTEA", "LUTEM", "LUTEO", "LUTOU", "LUVAS", "LUXAR", "LUXOU",
    "LUZES", "LUZIA", "LUZIO", "LUZIR", "LUZIU", "LYCRA", "LYGIA", "MIRZA", "MISSA", "MISSE",
    "MISSO", "MISTA", "MISTO", "MITOS", "MITRA", "MIUCA", "MIUDA", "MIUDO", "MIULO", "MIURA",
    "MIURO", "MIUVA", "MIXAR", "MIXER", "MIXIA", "MIXOU", "MIXTA", "MOAFA", "MOBIL", "MOCAO",
    "MOCAR", "MOCAS", "MOCHA", "MOCHO", "MOCOA", "MOCOS", "MOCSA", "MODAL", "MODAS", "MODEL",
    "MODEM", "MODOS", "MOEDA", "MOEGA", "MOELA", "MOEMA", "MOFAR", "MOFOU", "MOGAI", "MOGNO",
    "MOIAM", "MOIDA", "MOIDO", "MOINA", "MOIRA", "MOIRE", "MOIRO", "MOITA", "MOLAL", "MOLAR",
    "MOLAS", "MOLDA", "MOLDE", "MOLES", "MOLHA", "MOLHE", "MOLHO", "MONCO", "MONDE", "MONET",
    "MONGE", "MONGO", "MONHA", "MONHO", "MONIR", "MONJA", "MONOS", "MONTA", "MONTE", "MONTO",
    "MORAL", "MORAM", "MORAO", "MORAR", "MORAS", "MORBO", "MORDE", "MOREM", "MORES", "MORFE",
    "MORFO", "MORIA", "MORIM", "MORMO", "MORNA", "MORNO", "MOROU", "MORRA", "MORRE", "MORRI",
    "MORRO", "MORSA", "MORSE", "MORSO", "MORTA", "MORTE", "MORTO", "MOSCA", "MOSCO", "MOSSA",
    "MOSSO", "MOSTO", "MOTEL", "MOTES", "MOTIM", "MOTOR", "MOTOS", "MOTUS", "MOUCO", "MOURA",
    "MOURO", "MOUSE", "MOUTA", "MOVAM", "MOVEL", "MOVEM", "MOVER", "MOVEU", "MOVIA", "MOXAR",
    "MOZZA", "MUAFO", "MUAMA", "MUANA", "MUANE", "MUAVE", "MUCOL", "MUCRO", "MUCUA", "MUCUM",
    "MUDAM", "MUDAR", "MUDAS", "MUDEI", "MUDEM", "MUDEZ", "MUDOS", "MUDOU", "MUDRA", "MUFLA",
    "MUFTI", "MUGIR", "MUGUE", "MUITA", "MUITA", "MUITO", "MUJAS", "MULAS", "MULSO", "MULTA",
    "MULTI", "MUMIA", "MUNDA", "MUNDE", "MUNDI", "MUNDO", "MUNGE", "MUNGO", "MUNIR", "MUNIU",
    "MUNIZ", "MUNTZ", "MUNUS", "MUONS", "MUQUE", "MUQUI", "MURAL", "MURAR", "MURAS", "MURCA",
    "MURCO", "MUREX", "MURIA", "MUROS", "MUROU", "MURRA", "MURRO", "MURTA", "MURTO", "MURUI",
    "MUSAL", "MUSAS", "MUSEU", "MUSGO", "MUSIC", "MUSME", "MUSSE", "MUTUA", "MUTUM", "MUTUO",
    "MUUBA", "NAALI", "NABAL", "NABAO", "NABLA", "NABLO", "NABOS", "NACAO", "NACAR", "NACIP",
    "NADAK", "NADAM", "NADAR", "NADEM", "NADIR", "NADOU", "NAFIL", "NAFIR", "NAFTA", "NAGAO",
    "NAGOR", "NAGOS", "NAGUA", "NAIBE", "NAIFO", "NAIFS", "NAIPE", "NAIRA", "NAIRE", "NAJAS",
    "NALGA", "NAMAZ", "NAMBI", "NAMBU", "NAMOR", "NANAL", "NANAR", "NANAS", "NANDI", "NANDU",
    "NANJA", "NANUM", "NARDO", "NARIA", "NARIZ", "NARRA", "NASAL", "NASCA", "NASCE", "NASCI",
    "NASIO", "NASSA", "NATAL", "NATRO", "NAURU", "NAUTA", "NAVAL", "NAVES", "NAVIA", "NAVIO",
    "NAXIO", "NEBRI", "NECTO", "NEDIO", "NEFAS", "NEFRO", "NEGAM", "NEGAR", "NEGOU", "NEGRA",
    "NEGRE", "NEGRO", "NEGUS", "NEIDE", "NEIRA", "NEIVA", "NELAS", "NELES", "NEMBO", "NEMEU",
    "NENEM", "NENEN", "NENIA", "NEONS", "NEPAL", "NEPER", "NERDS", "NERES", "NEREU", "NERIO",
    "NEROL", "NERVA", "NERVO", "NESGA", "NESSA", "NESSE", "NESTA", "NESTE", "NETOS", "NEUMA",
    "NEURA", "NEURO", "NEUSA", "NEUZA", "NEVAR", "NEVER", "NEVES", "NEVIO", "NEVIS", "NEVOA",
    "NEVOU", "NHAPI", "NHATO", "NIAIA", "NICAR", "NICAS", "NICHO", "NICKS", "NICOL", "NIDOR",
    "NIEDE", "NIELO", "NIGER", "NIGUA", "NIKON", "NILGO", "NIMBO", "NIMES", "NIMIO", "NINAR",
    "NINFA", "NINHO", "NINJA", "NIOPO", "NIPLE", "NIPOA", "NIQAB", "NISEI", "NISIA", "NISSL",
    "NISSO", "NISTO", "NITRE", "NITRO", "NITXE", "NITXI", "NIVEL", "NIVEO", "NOBEL", "NOBRE",
    "NOCAO", "NODAL", "NODAR", "NODOA", "NODOS", "NOEMA", "NOEMI", "NOESE", "NOETE", "NOFRE",
    "NOGAI", "NOGAL", "NOITE", "NOIVA", "NOIVO", "NOMEA", "NOMES", "NONAS", "NONES", "NONIO",
    "NOPAL", "NOQUE", "NORAS", "NORCA", "NORMA", "NORTE", "NOSSA", "NOSSO", "NOTAM", "NOTAR",
    "NOTAS", "NOTEI", "NOTOU", "NOUTE", "NOVAL", "NOVAR", "NOVAS", "NOVEL", "NOVOS", "NOVOU",
    "NOXAL", "NOXIO", "NOYES", "NOZES", "NUBIA", "NUBIL", "NUBIO", "NUCAL", "NUCAO", "NUDEZ",
    "NUELO", "NUEZA", "NULAS", "NULOS", "NUMAS", "NUMBU", "NUNCA", "NUNES", "NUPES", "NURSE",
    "NUTAR", "NUTRE", "NUVEM", "NYLON", "OANDA", "OASIS", "OASKA", "OBEBA", "OBELO", "OBERA",
    "OBESA", "OBESO", "OBICE", "OBITO", "OBOES", "OBOLO", "OBORI", "OBRAM", "OBRAR", "OBRAS",
    "OBROU", "OBSTA", "OBTEM", "OBTER", "OBULO", "OBVIA", "OBVIO", "OBVIR", "OCADO", "OCAIM",
    "OCAPI", "OCARA", "OCASO", "OCELO", "OCIMO", "OCREA", "OCREM", "OCRES", "OCTAL", "OCTIL",
    "OCULO", "OCUPA", "ODARA", "ODEAO", "ODEIA", "ODEIO", "ODEOM", "ODEON", "ODEON", "ODIAR",
    "ODIEI", "ODILO", "ODIOS", "ODIOU", "ODITE", "ODORO", "ODRES", "OESTE", "OFAIE", "OFEGA",
    "OFEGO", "OFITO", "OFRIO", "OFRIS", "OFURO", "OGAMO", "OGANO", "OGIVA", "OGROS", "OIDIO",
    "OIRAR", "OITAO", "OLACE", "OLADA", "OLAIA", "OLAVO", "OLEAR", "OLEOL", "OLEOS", "OLEOU",
    "OLEUM", "OLHAL", "OLHAM", "OLHAR", "OLHEI", "OLHOS", "OLHOU", "OLIER", "OLIVA", "OLODE",
    "OLORI", "OMALA", "OMANI", "OMASO", "OMBRA", "OMBRO", "OMEGA", "OMELE", "OMITE", "OMOLU",
    "OMULU", "ONANI", "ONCAS", "ONDAR", "ONDAS", "ONERA", "ONFUA", "ONIXE", "ONONE", "ONTEM",
    "OPABA", "OPACA", "OPACO", "OPADO", "OPALA", "OPAVA", "OPCAO", "OPERA", "OPERA", "OPIAR",
    "OPIDO", "OPIMO", "OPINA", "OPLON", "OPOEM", "OPTAR", "OPTOU", "ORACA", "ORADA", "ORAGO",
    "ORAIS", "ORATE", "ORAVA", "ORCAR", "ORCAS", "ORCOU", "ORDEM", "OREAR", "OREIA", "ORFAO",
    "ORFAS", "ORFEU", "ORGAO", "ORGIA", "ORGIO", "ORIBI", "ORION", "ORIXA", "ORIZA", "ORKUT",
    "ORLAM", "ORLAR", "ORLAS", "ORLEA", "ORLOM", "ORLOU", "ORNAM", "ORNAR", "ORNIS", "ORNOU",
    "OROBO", "OROCO", "OROPA", "OROYA", "ORQUE", "ORSAT", "ORTIZ", "OSAKA", "OSCAR", "OSCOS",
    "OSKAR", "OSMAN", "OSMIO", "OSMOL", "OSONA", "OSRAM", "OSSEA", "OSSEO", "OSSOS", "OSTIO",
    "OSTRA", "OSTRO", "OTAVA", "OTICA", "OTICO", "OTIMA", "OTIMO", "OTITE", "OTONI", "OTOSE",
    "OUCAM", "OUCAS", "OURAR", "OUREM", "OUROS", "OUROU", "OUSAM", "OUSAR", "OUSIO", "OUSOU",
    "OUTAO", "OUTAR", "OUTRA", "OUTRO", "OUVEM", "OUVIA", "OUVIR", "OUVIU", "OVADA", "OVADO",
    "OVAIS", "OVALO", "OVANO", "OVENS", "OVEVA", "OVIDE", "OVINO", "OVNIS", "OVULO", "OXALA",
    "OXIDA", "OXIDE", "OXIDO", "OXIMA", "OXINA", "OXOCE", "OZENA", "OZONA", "OZONE", "PITUA",
    "PITUI", "PIUBA", "PIUCA", "PIUNA", "PIXEL", "PIXEU", "PIXUA", "PIZZA", "PLACA", "PLACE",
    "PLAGA", "PLANA", "PLANO", "PLATO", "PLAYS", "PLEBE", "PLENA", "PLENO", "PLEXO", "PLICA",
    "PLOTZ", "PLUMA", "PLUSH", "PLUTO", "PNEUS", "POACU", "POAIA", "POBRE", "POCAO", "POCAR",
    "POCAS", "POCHE", "POCOS", "PODAL", "PODAO", "PODAR", "PODAS", "PODEM", "PODER", "PODES",
    "PODIA", "PODIO", "PODOA", "PODOI", "PODOU", "PODRE", "POEJO", "POEMA", "POETA", "POIAL",
    "POIAR", "POILU", "POINT", "POIRE", "POISA", "POISE", "POISO", "POITA", "POJAR", "POLAR",
    "POLCA", "POLEM", "POLEN", "POLEX", "POLHA", "POLHO", "POLIA", "POLIO", "POLIR", "POLME",
    "POLMO", "POLOS", "POLPA", "POLUI", "POLVO", "POMAR", "POMAS", "POMBA", "POMBO", "POMES",
    "POMOS", "POMPA", "PONCA", "PONCO", "PONDO", "PONEI", "PONGA", "PONGO", "PONHA", "PONHO",
    "PONJE", "PONOM", "PONTA", "PONTE", "PONTI", "PONTO", "POPAO", "PORAO", "PORCA", "PORCO",
    "POREI", "POREM", "PORNO", "POROS", "PORRA", "PORRE", "PORRO", "PORTA", "PORTE", "PORTO",
    "POSAR", "POSES", "POSOU", "POSPO", "POSSA", "POSSE", "POSSO", "POSTA", "POSTE", "POSTO",
    "POTEM", "POTES", "POTIN", "POTRA", "POTRO", "POTUM", "POUCA", "POUCO", "POUND", "POUPA",
    "POUSA", "POUSO", "POUTA", "POVAO", "POVOA", "POVOA", "POVOS", "PRACA", "PRADO", "PRAGA",
    "PRAIA", "PRAJA", "PRANA", "PRASE", "PRATA", "PRATO", "PRAVO", "PRAXE", "PRAZO", "PREAR",
    "PREAS", "PRECE", "PRECO", "PREDA", "PREGA", "PREGO", "PREIA", "PREJU", "PRELO", "PREMA",
    "PREME", "PRESA", "PRESO", "PRETA", "PRETO", "PREVE", "PREZA", "PRIMA", "PRIME", "PRIMO",
    "PRINO", "PRION", "PRIOR", "PRISE", "PRIVA", "PRIVE", "PROAR", "PROAS", "PROBO", "PROCA",
    "PROIZ", "PROLE", "PRONA", "PRONO", "PRONY", "PROSA", "PROTO", "PROVA", "PROVE", "PROVO",
    "PRUCA", "PRUIR", "PRUMO", "PRUNO", "PRURE", "PSECA", "PSOAS", "PSORA", "PTOSE", "PUACO",
    "PUACU", "PUADO", "PUAVA", "PUBAR", "PUBAS", "PUBIS", "PUCHA", "PUCHO", "PUDER", "PUDIM",
    "PUDOR", "PUERA", "PUGIL", "PUGNA", "PUIDA", "PUIDO", "PUITA", "PUJAR", "PULAR", "PULEI",
    "PULEM", "PULES", "PULGA", "PULGO", "PULHA", "PULOS", "PULOU", "PULSA", "PULSO", "PUMBA",
    "PUNCH", "PUNGA", "PUNGE", "PUNHA", "PUNHO", "PUNIR", "PUNIU", "PUPAL", "PUPAS", "PURAS",
    "PUREO", "PUREU", "PURGA", "PURIS", "PUROS", "PURUI", "PURUS", "PUSER", "PUSEY", "PUTAL",
    "PUTAS", "PUTIS", "PUXAM", "PUXAO", "PUXAR", "PUXEI", "PUXOU", "PYREX", "QUADO", "QUAIS",
    "QUARA", "QUARK", "QUARO", "QUART", "QUASE", "QUATA", "QUATI", "QUEBA", "QUECE", "QUEDA",
    "QUEDE", "QUEDO", "QUELA", "QUELE", "QUENA", "QUEPE", "QUERA", "QUERO", "QUETO", "QUIBA",
    "QUIBE", "QUICA", "QUICE", "QUICO", "QUILO", "QUIMO", "QUINA", "QUINO", "QUIPA", "QUIPO",
    "QUIRI", "QUITA", "QUITE", "QUITI", "QUITO", "QUIUI", "QUIVI", "QUIXO", "QUOTA", "RABAO",
    "RABAT", "RABAZ", "RABIA", "RABIL", "RABOS", "RACAO", "RACAS", "RACHA", "RACHE", "RACKS",
    "RACLE", "RACOR", "RACUM", "RADAR", "RADIA", "RADIO", "RAFAR", "RAFES", "RAFIA", "RAFOU",
    "RAGLA", "RAIAL", "RAIAM", "RAIAR", "RAIAS", "RAIDE", "RAIOM", "RAIOS", "RAIOU", "RAIVA",
    "RAJAO", "RAJAR", "RAJAS", "RAJOU", "RALAR", "RALAS", "RALES", "RALHA", "RALHE", "RALHO",
    "RALLY", "RALOS", "RALOU", "RALPH", "RAMAL", "RAMAS", "RAMEO", "RAMNO", "RAMOS", "RAMPA",
    "RAMUS", "RANCA", "RANCO", "RANGE", "RANGO", "RANHO", "RAPAR", "RAPAZ", "RAPEL", "RAPOU",
    "RAPTO", "RAQUE", "RAQUI", "RARAS", "RAROS", "RASAR", "RASAS", "RASCA", "RASES", "RASGA",
    "RASGO", "RASOS", "RASPA", "RASPE", "RASTA", "RASTO", "RATAO", "RATAR", "RATEL", "RATOS",
    "RATTO", "RAVER", "RAZAO", "REACA", "REAGE", "REAIS", "REAJA", "REATA", "REATE", "REATO",
    "REAVE", "REBEM", "REBOA", "REBOO", "REBUS", "RECAI", "RECEM", "RECHA", "RECIA", "RECIT",
    "RECRU", "RECUA", "RECUE", "RECUO", "REDAR", "REDEA", "REDEM", "REDES", "REDIA", "REDIL",
    "REDOR", "REDOX", "REDRA", "REDUZ", "REFAZ", "REFEM", "REFEZ", "REFIL", "REFLE", "REFRI",
    "REGAL", "REGAR", "REGAS", "REGEM", "REGER", "REGEU", "REGIA", "REGIO", "REGMA", "REGOS",
    "REGOU", "REGRA", "REGUA", "REICH", "REIDE", "REIKI", "REIMA", "REINA", "REINO", "REIRA",
    "REIXA", "RELAR", "RELAS", "RELAX", "RELER", "RELES", "RELEU", "RELHA", "RELHO", "RELIA",
    "RELOU", "RELUZ", "RELVA", "REMAM", "REMAR", "REMIR", "REMIU", "REMIX", "REMOI", "REMOS",
    "RENAL", "RENAN", "RENAO", "RENAS", "RENDA", "RENDE", "RENGA", "RENGO", "RENIO", "RENTE",
    "RENUI", "REPES", "REPOE", "REPOR", "REPOS", "REPTA", "REPTO", "REQUE", "RERIU", "RESES",
    "RESMA", "RESPE", "RESTA", "RESTE", "RESTO", "RETAL", "RETAR", "RETAS", "RETEM", "RETER",
    "RETOR", "RETOS", "RETRE", "RETRO", "REUMA", "REUNE", "REUSO", "REVEL", "REVER", "REVES",
    "REVIA", "REVIR", "REVIU", "REVMA", "REVOO", "REZAM", "REZAO", "REZAR", "REZAS", "REZOU",
    "RIADE", "RIBES", "RICAR", "RICAS", "RICIO", "RICOS", "RICTO", "RIFAO", "RIFAR", "RIFLE",
    "RIFOU", "RIFTE", "RIGAR", "RIGOR", "RIJAS", "RIJOS", "RILHA", "RIMAM", "RIMAR", "RIMAS",
    "RIMEL", "RIMET", "RIMOS", "RINDO", "RINHA", "RIPAL", "RIPAO", "RIPAR", "RIPAS", "RIPIO",
    "RIPOU", "RIRAM", "RIREM", "RISAO", "RISCA", "RISCO", "RISOS", "RISTE", "RITMO", "RITON",
    "RITOS", "RIVAL", "RIXAR", "RIXAS", "RIZAR", "RIZES", "ROAST", "ROBLE", "ROBOS", "ROCAL",
    "ROCAM", "ROCAR", "ROCAS", "ROCAZ", "ROCHA", "ROCIM", "ROCIO", "ROCLO", "ROCOU", "RODAM",
    "RODAO", "RODAR", "RODAS", "RODEA", "RODES", "RODIN", "RODIO", "RODOS", "RODOU", "ROGAL",
    "ROGAR", "ROGOS", "ROGOU", "ROIDO", "ROJAM", "ROJAO", "ROJAR", "ROLAM", "ROLAO", "ROLAR",
    "ROLAS", "ROLDA", "ROLHA", "ROLHO", "ROLOS", "ROLOU", "ROMAN", "ROMAO", "ROMBO", "ROMEU",
    "ROMPE", "RONCA", "RONCO", "RONCO", "RONDA", "RONDO", "RONGA", "RONGO", "RONHA", "ROQUE",
    "RORAR", "ROSAL", "ROSAR", "ROSAS", "ROSCA", "ROSEA", "ROSEO", "ROSNA", "ROSOU", "ROSTO",
    "ROTAR", "ROTAS", "ROTIM", "ROTOR", "ROUBA", "ROUBO", "ROUCA", "ROUCO", "ROUGE", "ROUND",
    "ROUPA", "ROXAS", "ROXOS", "ROYAL", "RUACA", "RUANO", "RUBEM", "RUBEO", "RUBIM", "RUBIS",
    "RUBLO", "RUBOR", "RUBRA", "RUBRO", "RUCAR", "RUCHE", "RUCOU", "RUDES", "RUDEZ", "RUDOS",
    "RUELA", "RUFAM", "RUFAR", "RUFIA", "RUFIO", "RUFLA", "RUFLO", "RUFOS", "RUFOU", "RUGAR",
    "RUGAS", "RUGBI", "RUGEM", "RUGIA", "RUGIR", "RUGIU", "RUIDO", "RUINA", "RUINS", "RUIRA",
    "RUIVA", "RUIVO", "RULAR", "RUMAR", "RUMBA", "RUMEN", "RUMES", "RUMEX", "RUMOR", "RUMOS",
    "RUMPI", "RUNAS", "RUNDO", "RUPIA", "RURAL", "RUSCO", "RUSGA", "RUSMA", "RUSSA", "RUSSE",
    "RUSSO", "RUSTE", "RUSTO", "SIUBA", "SIUSI", "SIUVA", "SIVAN", "SKANK", "SKATE", "SKENE",
    "SKYPE", "SLACK", "SLANG", "SLIDE", "SLOTS", "SMITH", "SNIPE", "SOADA", "SOADO", "SOARA",
    "SOAVA", "SOBAS", "SOBEM", "SOBIA", "SOBPE", "SOBRA", "SOBRE", "SOBRO", "SOCAR", "SOCIA",
    "SOCIO", "SOCLO", "SOCOI", "SOCOS", "SOCOS", "SOCOU", "SODAR", "SODIO", "SODRA", "SODRE",
    "SOFAS", "SOFIA", "SOFRA", "SOFRE", "SOFRI", "SOFRO", "SOFTA", "SOGAR", "SOGRA", "SOGRO",
    "SOGUA", "SOIDO", "SOIPE", "SOITO", "SOLAO", "SOLAR", "SOLAS", "SOLAU", "SOLAZ", "SOLDA",
    "SOLDO", "SOLEA", "SOLES", "SOLFA", "SOLHA", "SOLHO", "SOLIA", "SOLIO", "SOLON", "SOLOS",
    "SOLTA", "SOLTE", "SOLTO", "SOLVE", "SOMAM", "SOMAR", "SOMAS", "SOMIE", "SOMOS", "SONAR",
    "SONDA", "SONHA", "SONHO", "SONIA", "SONSA", "SONSO", "SOPAS", "SOPES", "SOPOR", "SOPRA",
    "SOPRO", "SOQUE", "SORAL", "SORAR", "SORBO", "SORDA", "SOREN", "SORGO", "SORIA", "SORNA",
    "SOROR", "SOROS", "SORRI", "SORRO", "SORTE", "SORVA", "SORVE", "SORVO", "SOSIA", "SOSSA",
    "SOSSO", "SOTAO", "SOTAS", "SOUBE", "SOULS", "SOURE", "SOUSA", "SOUTO", "SOUZA", "SOVAR",
    "SOVEI", "SOVEU", "SOVOU", "SPAMS", "SPINS", "SPLIT", "SPOTS", "SPRAY", "SQUID", "STAFF",
    "STAND", "STARS", "STEIN", "STENT", "STILB", "STILL", "STOLL", "STOPS", "STOUT", "STRIP",
    "STURM", "SUACU", "SUADA", "SUADO", "SUARI", "SUAVA", "SUAVE", "SUAZI", "SUBER", "SUBIA",
    "SUBIR", "SUBIU", "SUCAO", "SUCIA", "SUCIO", "SUCOS", "SUCRE", "SUDAO", "SUDRA", "SUDRO",
    "SUECA", "SUECO", "SUEDA", "SUEDE", "SUELY", "SUETO", "SUEVO", "SUFLE", "SUGAM", "SUGAR",
    "SUGOU", "SUIAS", "SUICA", "SUICO", "SUINA", "SUINO", "SUITE", "SUJAR", "SUJAS", "SUJEM",
    "SUJOS", "SUJOU", "SULAO", "SULCA", "SULCO", "SULFA", "SUMAS", "SUMIA", "SUMIR", "SUMIU",
    "SUNDO", "SUNFA", "SUNGA", "SUNTO", "SUPOE", "SUPOR", "SUPOS", "SUPRA", "SUPRE", "SURAL",
    "SURDA", "SURDO", "SURFA", "SURFE", "SURGE", "SURIM", "SURJA", "SURRA", "SURRE", "SURRO",
    "SURTO", "SURUI", "SUSHI", "SUSTO", "SUTAR", "SUTIA", "SUTIL", "SUTIS", "SUTRA", "SUXAR",
    "SUXOU", "SWAPS", "SWELL", "SWIFT", "SWING", "TORNA", "TORNE", "TORNO", "TOROS", "TORPE",
    "TORRA", "TORRE", "TORSO", "TORTA", "TORTO", "TORVA", "TORVO", "TOSAO", "TOSAR", "TOSCA",
    "TOSCO", "TOSOU", "TOSSE", "TOSTA", "TOSTE", "TOTAL", "TOTEM", "TOUCA", "TOUCH", "TOURO",
    "TOURS", "TOUTA", "TOXIN", "TRACA", "TRACO", "TRADO", "TRAGA", "TRAGO", "TRAIA", "TRAIN",
    "TRAIR", "TRAIU", "TRAJA", "TRAJE", "TRAJO", "TRAMA", "TRAMO", "TRANS", "TRAPA", "TRAPE",
    "TRAPO", "TRARA", "TRATA", "TRATE", "TRATO", "TRAVA", "TRAVE", "TRAVO", "TRAZE", "TRECO",
    "TRECO", "TREDO", "TREFO", "TRELA", "TRELE", "TREMA", "TREME", "TREMO", "TRENA", "TRENO",
    "TRENS", "TREPA", "TRESO", "TRETA", "TREVA", "TREVO", "TREZE", "TRIAL", "TRIAR", "TRIAS",
    "TRIBO", "TRICA", "TRICO", "TRIDI", "TRIES", "TRIGA", "TRIGO", "TRILA", "TRILO", "TRINA",
    "TRINO", "TRIOS", "TRIPA", "TRIPE", "TRIPO", "TRIPS", "TROAR", "TROCA", "TROCO", "TROIA",
    "TROIS", "TROLE", "TRONA", "TRONO", "TROPA", "TROPO", "TROTA", "TROTE", "TROVA", "TRUAO",
    "TRUCA", "TRUCO", "TRUDE", "TRUFA", "TRUPE", "TRUTA", "TUAIA", "TUBAR", "TUBAS", "TUBEL",
    "TUBIM", "TUBOS", "TUCAO", "TUCHO", "TUCUM", "TUDEL", "TUDOR", "TUFAM", "TUFAO", "TUFAR",
    "TUFOS", "TUFOU", "TUGIR", "TUGUE", "TUIRA", "TULHA", "TULIO", "TUMBA", "TUMOR", "TUNAL",
    "TUNAR", "TUNCO", "TUNDA", "TUNEL", "TUNGA", "TUNIS", "TUPIA", "TUPIS", "TUQUE", "TURBA",
    "TURBO", "TURCA", "TURCO", "TURDO", "TURFA", "TURFE", "TURIM", "TURKS", "TURMA", "TURNE",
    "TURNO", "TURRA", "TURVA", "TURVO", "TUSSI", "TUSTA", "TUTEA", "TUTIA", "TUTOR", "TUTSI",
    "TUTTI", "TWEED", "TWIST", "TYLOR", "UAICU", "UAIAS", "UAICA", "UAIPI", "UAITA", "UAIUA",
    "UARIA", "UARIS", "UASCA", "UASSU", "UAURA", "UAXUA", "UBAIA", "UBARI", "UBATA", "UBEBA",
    "UBERE", "UBUCU", "UCHAO", "UCHOA", "UESFA", "UFANA", "UFANO", "UIARA", "UIBAI", "UIQUE",
    "UISTE", "UIVAR", "UIVOS", "UIVOU", "ULANO", "ULEMA", "ULIIA", "ULITE", "ULNAL", "ULOMA",
    "ULREI", "ULTOR", "ULTRA", "ULULA", "ULULO", "ULURI", "UMARE", "UMARI", "UMBRA", "UMBRO",
    "UMBUS", "UMERO", "UMIDA", "UMIDO", "UMIRI", "UNCAO", "UNCIA", "UNCUS", "UNGIA", "UNGIR",
    "UNGIU", "UNGUE", "UNGUI", "UNHAO", "UNHAR", "UNHAS", "UNHEI", "UNHOU", "UNIAO", "UNICA",
    "UNICO", "UNIDA", "UNIDO", "UNIRA", "UNTAM", "UNTAR", "UNTOU", "URACA", "URACO", "URACU",
    "URAIS", "URALI", "URANO", "URARE", "URARI", "URATO", "URDIR", "URDIU", "UREDO", "UREIA",
    "URERA", "URGIA", "URGIR", "URGIU", "URIAS", "URICA", "URICO", "URINA", "URNAS", "URRAR",
    "URROS", "URSOS", "URUBA", "URUBU", "URUCU", "URUMA", "URUMI", "URUPA", "URUPE", "URURI",
    "URUTU", "URUXI", "URZAL", "URZES", "USADA", "USADO", "USARA", "USAVA", "USINA", "USNEA",
    "USQUE", "USTAO", "USUAL", "USURA", "UTEIS", "UTERO", "UVACA", "UVAIA", "UVULA", "VACAL",
    "VACAO", "VACAR", "VACAS", "VACUA", "VACUM", "VACUO", "VADIA", "VADIO", "VAFRO", "VAGAL",
    "VAGAM", "VAGAO", "VAGAR", "VAGAS", "VAGEM", "VAGIR", "VAGOS", "VAGOU", "VAGUE", "VAIAR",
    "VAIAS", "VAIOU", "VAIXA", "VALAO", "VALAR", "VALAS", "VALDO", "VALEM", "VALER", "VALES",
    "VALET", "VALEU", "VALGO", "VALHA", "VALIA", "VALOR", "VALOS", "VALOU", "VALSA", "VALVA",
    "VAMOS", "VAMPE", "VAMPI", "VANCE", "VANTE", "VAPOR", "VARAL", "VARAO", "VARAR", "VARAS",
    "VARGA", "VARIA", "VARIO", "VARIZ", "VARJA", "VAROA", "VAROU", "VARRE", "VARVA", "VARVE",
    "VARVO", "VASCA", "VASCO", "VASOS", "VASTA", "VASTO", "VATER", "VAZAM", "VAZAO", "VAZAR",
    "VAZAS", "VAZIA", "VAZIO", "VAZOU", "VEADA", "VEADO", "VEDAR", "VEDAS", "VEDES", "VEDOR",
    "VEDOU", "VEDRO", "VEIAR", "VEIAS", "VEIGA", "VEIOS", "VEIRO", "VEJAM", "VELAR", "VELAS",
    "VELEM", "VELHA", "VELHO", "VELOU", "VELOZ", "VELUM", "VELVI", "VEMOS", "VENAL", "VENCA",
    "VENCE", "VENCO", "VENDA", "VENDE", "VENDI", "VENDO", "VENHA", "VENHO", "VENIA", "VENTA",
    "VENTO", "VENUS", "VERAO", "VERAS", "VERAZ", "VERBA", "VERBO", "VERCA", "VERDE", "VEREM",
    "VERGA", "VERGE", "VERIA", "VERME", "VERNO", "VERSA", "VERSO", "VERTE", "VERVE", "VESCO",
    "VESGO", "VESPA", "VESTA", "VESTE", "VESTI", "VETAR", "VETOR", "VETOU", "VEXAR", "VEXOU",
    "VEZAR", "VEZES", "VIADO", "VIAJA", "VIAJO", "VIANA", "VIBRA", "VICAR", "VICHI", "VICHY",
    "VICIA", "VICIO", "VIDAL", "VIDAO", "VIDAR", "VIDAS", "VIDEO", "VIDES", "VIDIA", "VIDRA",
    "VIDRO", "VIELA", "VIENA", "VIERA", "VIGAR", "VIGAS", "VIGEM", "VIGER", "VIGIA", "VIGIL",
    "VIGOR", "VIGOU", "VILAO", "VILAR", "VILAS", "VILLE", "VILOA", "VILTA", "VIMES", "VIMOS",
    "VINCA", "VINCI", "VINCO", "VINDA", "VINDO", "VINEO", "VINGA", "VINHA", "VINHO", "VINIL",
    "VINIS", "VINTE", "VIOLA", "VIOLE", "VIRAL", "VIRAM", "VIRAO", "VIRAR", "VIREI", "VIRES",
    "VIRGA", "VIRGO", "VIRIA", "VIRIL", "VIRIS", "VIROU", "VIRUS", "VISAM", "VISAO", "VISAR",
    "VISCO", "VISEM", "VISEU", "VISGO", "VISON", "VISOR", "VISOS", "VISOU", "VISSE", "VISTA",
    "VISTE", "VISTO", "VITAL", "VITEX", "VITIS", "VITRO", "VITRO", "VIUVA", "VIUVO", "VIVAM",
    "VIVAR", "VIVAS", "VIVAZ", "VIVEM", "VIVER", "VIVES", "VIVEU", "VIVIA", "VIVOS", "VIXNU",
    "VIZIR", "VOARA", "VOAVA", "VOCAL", "VOCES", "VODCA", "VODUM", "VODUS", "VOEJA", "VOEJO",
    "VOGAL", "VOGAM", "VOGAR", "VOGAS", "VOGOU", "VOILE", "VOLAR", "VOLEI", "VOLPI", "VOLTA",
    "VOLTE", "VOLTO", "VOLTS", "VOLVA", "VOLVE", "VOLVO", "VOMER", "VONCE", "VORAZ", "VOSSA",
    "VOSSO", "VOTAM", "VOTAR", "VOTOS", "VOTOU", "VOUVE", "VOZAO", "VOZES", "VULGO", "VULTO",
    "VULVA", "VUMBE", "VUNGE", "VUNJE", "VURMO", "WHATS", "XACRA", "XADOR", "XAILE", "XAMPU",
    "XANGO", "XANTO", "XAORO", "XAQUE", "XARDA", "XAREM", "XAREU", "XARIA", "XAUAL", "XAUIM",
    "XAXIM", "XELIM", "XELMA", "XENIA", "XENIO", "XENON", "XEQUE", "XEREM", "XEREU", "XEREZ",
    "XERGA", "XEROX", "XEROX", "XERVA", "XETAS", "XEURA", "XEXEM", "XEXEU", "XIBIO", "XIBIU",
    "XIITA", "XILOL", "XIMAO", "XIMBE", "XIMBO", "XIMBO", "XINGA", "XINGO", "XINGU", "XINTO",
    "XIRIS", "XISTO", "XOANA", "XOANO", "XOCOS", "XOGUM", "XOGUM", "XONAS", "XOTIS", "XUATE",
    "XUCRO", "YACHT", "YAHVE", "ZAGAL", "ZAIBO", "ZAIMO", "ZAINO", "ZAIRE", "ZAMBE", "ZAMBE",
    "ZAMBI", "ZAMBI", "ZAMBO", "ZAMIA", "ZANGA", "ZANHO", "ZANNI", "ZANZO", "ZARCO", "ZARGO",
    "ZARIA", "ZARRO", "ZARZA", "ZEBRA", "ZEBUS", "ZEFIR", "ZEGRI", "ZELAM", "ZELAR", "ZELHA",
    "ZELOS", "ZELOU", "ZENAO", "ZENDA", "ZENDE", "ZERAR", "ZEROS", "ZEROU", "ZESTO", "ZEUGO",
    "ZILDA", "ZIMBO", "ZINCO", "ZINGA", "ZINHA", "ZINHO", "ZINIA", "ZINIR", "ZIPAR", "ZIPER",
    "ZIRRE", "ZIRRO", "ZIZIO", "ZOADA", "ZOAVA", "ZOEIA", "ZOICO", "ZOILO", "ZOMBA", "ZOMBA",
    "ZONAL", "ZONAR", "ZONAS", "ZONZO", "ZOOMS", "ZOOSE", "ZORRA", "ZORRO", "ZUAVO", "ZUMBA",
    "ZUMBE", "ZUMBI", "ZUMBO", "ZUNDA", "ZUNGA", "ZUNGU", "ZUNHI", "ZUNIR", "ZUNIU", "ZUNJA",
    "ZUPAR", "ZURNA", "ZURRA", "ZURRE", "ZURRO", "ZURUO", "ZURZE", "MASSA", "MARTE", "MILTO", "PASSA", "PASSO", "PISCA","TERMO"
];

// === MONGODB ===
mongoose.connect(process.env.MONGO_URI)
    .then(() => console.log('✅ MongoDB Conectado'))
    .catch(err => console.error('❌ Erro Mongo:', err));

const userSchema = new mongoose.Schema({
    googleId: { type: String, required: true, unique: true },
    username: String,
    avatar: String,
    score: { type: Number, default: 0 },
    energy: { type: Number, default: 5 }, 
    wins: { type: Number, default: 0 },
    gamesPlayed: { type: Number, default: 0 },
    lastIp: String,
    lastDailyLogin: { type: Date, default: Date.now }, 
    createdAt: { type: Date, default: Date.now }
});
userSchema.index({ googleId: 1 });
const User = mongoose.model('User', userSchema);

// === PASSPORT ===
passport.use(new GoogleStrategy({
    clientID: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    callbackURL: "/auth/google/callback"
  },
  async (accessToken, refreshToken, profile, done) => {
    try {
        let user = await User.findOneAndUpdate(
            { googleId: profile.id },
            { 
                $setOnInsert: { 
                    username: profile.displayName,
                    avatar: profile.photos[0].value,
                    energy: 5
                }
            },
            { new: true, upsert: true }
        );
        return done(null, user);
    } catch (err) { return done(err, null); }
  }
));

passport.serializeUser((user, done) => done(null, user.id));
passport.deserializeUser((id, done) => User.findById(id).then(u => done(null, u)).catch(e => done(e)));

// === MIDDLEWARES ===
const isProduction = process.env.NODE_ENV === 'production';

const sessionMiddleware = session({
    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: false,
    store: MongoStore.create({ mongoUrl: process.env.MONGO_URI }),
    cookie: { 
        maxAge: 24 * 60 * 60 * 1000, 
        secure: isProduction, 
        sameSite: isProduction ? 'none' : 'lax' 
    }
});

const loginLimiter = rateLimit({
    windowMs: 60 * 1000, max: 15, message: "Muitas tentativas.",
    standardHeaders: true, legacyHeaders: false,
});

app.use(express.static(path.join(__dirname, 'public')));
app.use(sessionMiddleware);
app.use(passport.initialize());
app.use(passport.session());

const wrap = middleware => (socket, next) => middleware(socket.request, {}, next);
io.use(wrap(sessionMiddleware));
io.use(wrap(passport.initialize()));
io.use(wrap(passport.session()));

io.use((socket, next) => {
    if (socket.request.user) next();
    else next(new Error('unauthorized'));
});

// === ROTAS ===
app.use('/auth/google', loginLimiter, (req, res, next) => {
    if (req.user) return next();
    if (io.engine.clientsCount >= MAX_GLOBAL_PLAYERS) return res.status(503).send('Servidor Lotado! Tente mais tarde.');
    next();
});

app.get('/auth/google', passport.authenticate('google', { scope: ['profile'] }));
app.get('/auth/google/callback', passport.authenticate('google', { failureRedirect: '/' }), (req, res) => res.redirect('/'));
app.get('/auth/logout', (req, res, next) => { req.logout(err => { if(err) return next(err); res.redirect('/'); }); });
app.get('/api/me', (req, res) => { if (!req.user) return res.status(401).json({ error: 'Not logged' }); res.json(req.user); });
app.get('/api/leaderboard', async (req, res) => {
    try { const players = await User.find().sort({ score: -1 }).limit(20).select('username score avatar wins'); res.json(players); } 
    catch(e) { res.status(500).json([]); }
});

// === ESTADO GLOBAL ===
const rooms = {};
// Armazena timers de desconexão: { "userId": TimeoutObject }
const disconnectTimers = {};

function generateRoomId() { return Math.floor(100000 + Math.random() * 900000).toString(); }

function emitRoomList() {
    const availableRooms = Object.values(rooms)
        .filter(r => r.isPublic && Object.keys(r.players).length < r.maxPlayers && r.state === 'LOBBY')
        .map(r => ({
            id: r.id, hostName: r.players[r.host]?.name || '?', playerCount: Object.keys(r.players).length,
            maxPlayers: r.maxPlayers, gameMode: r.gameMode
        }));
    io.emit('updateRoomList', availableRooms);
}

function emitPlayerUpdates(roomId) {
    const room = rooms[roomId];
    if (!room) return;
    const list = Object.values(room.players);
    io.to(roomId).emit('updatePlayerList', list, room.maxPlayers);
    io.to(roomId).emit('updateScoreboard', list);
    emitRoomList();
}

async function checkDailyReset(userId) {
    try {
        const user = await User.findById(userId);
        if (!user) return null;
        const now = new Date();
        const lastLogin = new Date(user.lastDailyLogin);
        const isDifferentDay = now.getDate() !== lastLogin.getDate() || now.getMonth() !== lastLogin.getMonth() || now.getFullYear() !== lastLogin.getFullYear();

        if (isDifferentDay) {
            if (user.energy < 5) user.energy = 5;
            user.lastDailyLogin = now;
            await user.save();
        } else {
            user.lastDailyLogin = now;
            await user.save();
        }
        return user;
    } catch (e) { return null; }
}

// === SOCKET LOGIC ===
io.on('connection', async (socket) => {
    const user = socket.request.user;
    const userId = user._id.toString();

    // Bloqueia se servidor lotado (mas permite reconexão se já estiver na lista)
    // Se o user tem um timer de disconnect, significa que ele está reconectando, então deixamos passar
    if((!user || io.engine.clientsCount > MAX_GLOBAL_PLAYERS) && !disconnectTimers[userId]) { 
        socket.disconnect(); 
        return; 
    }

    const dbUser = await checkDailyReset(userId);
    if (!dbUser) { socket.disconnect(); return; }

    console.log(`Conexão: ${dbUser.username} (ID: ${socket.id})`);
    
    // === LÓGICA DE RECONEXÃO ===
    // Se este usuário tinha acabado de cair, cancelamos a expulsão dele
    if (disconnectTimers[userId]) {
        console.log(`♻️ ${dbUser.username} voltou antes do tempo acabar! Cancelando expulsão.`);
        clearTimeout(disconnectTimers[userId]);
        delete disconnectTimers[userId];

        // Procurar qual sala ele estava e atualizar o socket ID
        for (const roomId in rooms) {
            const room = rooms[roomId];
            // Procura o jogador pelo ID do Banco de Dados (não pelo socket antigo que morreu)
            const oldSocketId = Object.keys(room.players).find(sid => room.players[sid].dbId.toString() === userId);

            if (oldSocketId) {
                // Recupera os dados do jogador
                const playerData = room.players[oldSocketId];
                
                // Remove a chave antiga e cria a nova com o novo Socket ID
                delete room.players[oldSocketId];
                playerData.id = socket.id; // Atualiza ID
                room.players[socket.id] = playerData; // Salva com nova chave

                // Atualiza Host se necessário
                if (room.host === oldSocketId) {
                    room.host = socket.id;
                    socket.emit('youAreHost');
                }

                // Reconecta o socket na sala do Socket.IO
                socket.join(roomId);

                // Avisa o cliente que ele voltou pra sala
                socket.emit('roomJoined', { 
                    roomId: roomId, 
                    isHost: playerData.isHost, 
                    playerId: socket.id 
                });
                
                // Se o jogo já estava rolando, avisa o estado atual
                if(room.state === 'PLAYING') {
                    socket.emit('gameStarted', { gameMode: room.gameMode });
                    socket.emit('newRound', { roundNumber: room.currentRound, totalRounds: TOTAL_ROUNDS, gameMode: room.gameMode });
                    // Se ele já tinha chutado coisas, teria que repassar o estado (não implementado aqui para simplicidade, mas ele continua jogando a próxima)
                }

                emitPlayerUpdates(roomId);
                console.log(`✅ ${dbUser.username} reconectado na sala ${roomId}`);
                break; // Achou a sala, para de procurar
            }
        }
    }

    socket.emit('userDataUpdate', dbUser);
    emitRoomList();

    // --- FUNÇÃO DE SAÍDA DEFINITIVA ---
    async function executePlayerExit(roomId, socketId) {
        const room = rooms[roomId];
        if (!room || !room.players[socketId]) return;

        const player = room.players[socketId];
        console.log(`🚪 ${player.name} saiu definitivamente da sala ${roomId}`);

        const wasHost = player.isHost;
        delete room.players[socketId];
        
        if (Object.keys(room.players).length === 0) {
            clearInterval(room.timer);
            delete rooms[roomId];
            emitRoomList();
        } else {
            if (wasHost) {
                const remainingIds = Object.keys(room.players);
                const nextHostId = remainingIds[0];
                room.players[nextHostId].isHost = true;
                room.host = nextHostId;
                io.to(nextHostId).emit('youAreHost'); 
            }
            emitPlayerUpdates(roomId);
        }
    }

    socket.on('createRoom', async ({ isPublic, roomSize }) => {
        if (Object.keys(rooms).length >= MAX_ROOMS) return socket.emit('error', 'Muitas salas.');
        const u = await User.findById(user._id);
        if (u.energy < 1) return socket.emit('error', 'Sem energia!');

        let limit = parseInt(roomSize);
        if (isNaN(limit) || limit < 2) limit = 2;
        if (limit > 20) limit = 20;

        const roomId = generateRoomId();
        rooms[roomId] = {
            id: roomId, state: 'LOBBY', players: {}, host: socket.id,
            currentRound: 0, currentWord: "", timer: null, timeLeft: 0,
            solversCount: 0, isPublic: !!isPublic, maxPlayers: limit, gameMode: 'default'
        };
        joinRoomLogic(socket, roomId, u, true);
    });

    socket.on('joinRoom', async ({ roomId }) => {
        const u = await User.findById(user._id);
        if (u.energy < 1) return socket.emit('error', 'Sem energia!');
        const room = rooms[roomId];
        if (!room || (room.state !== 'LOBBY' && room.state !== 'ENDED') || Object.keys(room.players).length >= room.maxPlayers) return socket.emit('error', 'Indisponível.');
        joinRoomLogic(socket, roomId, u, false);
    });

    function joinRoomLogic(socket, roomId, dbUser, isHost) {
        const room = rooms[roomId];
        socket.join(roomId);
        room.players[socket.id] = {
            id: socket.id, dbId: dbUser._id, name: dbUser.username, avatar: dbUser.avatar,
            roomId: roomId, isHost: isHost, score: 0, wins: 0, solvedRound: false, roundAttempts: 0
        };
        socket.emit('roomJoined', { roomId, isHost, playerId: socket.id });
        emitPlayerUpdates(roomId);
    }

    socket.on('chatMessage', ({ roomId, msg }) => {
        const room = rooms[roomId];
        if(room && room.players[socket.id]) {
            io.to(roomId).emit('chatMessage', { playerId: room.players[socket.id].dbId, playerName: room.players[socket.id].name, msg: msg.substring(0, 100) });
        }
    });

    socket.on('startGame', async ({ roomId, gameMode }) => {
        const room = rooms[roomId];
        if (!room || room.host !== socket.id) return;
        if (Object.keys(room.players).length < 2) return socket.emit('error', 'Mínimo 2 jogadores.');

        const playerSocketIds = Object.keys(room.players);
        for (const socketId of playerSocketIds) {
            const player = room.players[socketId];
            const updatedUser = await User.findByIdAndUpdate(
                player.dbId, 
                { $inc: { energy: -1, gamesPlayed: 1 } },
                { new: true }
            );
            io.to(socketId).emit('userDataUpdate', updatedUser);
        }

        room.gameMode = gameMode; room.state = 'PLAYING';
        io.to(roomId).emit('gameStarted', { gameMode });
        emitRoomList();
        startRound(roomId);
    });

    socket.on('submitGuess', async ({ roomId, guess }) => {
        const room = rooms[roomId];
        if (!room) return;
        if (room.state !== 'PLAYING' && room.state !== 'TIEBREAKER') return;

        const player = room.players[socket.id];
        if (room.state === 'TIEBREAKER' && !room.tiedPlayersIds.includes(socket.id)) return;

        if (player.solvedRound) return;
        if (WORDS.length > 0 && !WORDS.includes(guess)) return;

        player.roundAttempts++;
        const result = calculateWordleResult(guess, room.currentWord);
        const isCorrect = result.every(r => r === 'correct');

        socket.emit('guessResult', { guess, result });

        if (isCorrect) {
            player.solvedRound = true; room.solversCount++;
            let points = 0;
            if (room.state === 'TIEBREAKER') {
                player.score += 1;
                io.to(roomId).emit('roundSuccess', `${player.name} É O GOAT SUPREMO!`);
                endGameFinal(roomId);
                return;
            }
            if (room.gameMode === 'competitive') {
                points = Math.max(1, 11 - player.roundAttempts);
                player.score += points;
                User.findByIdAndUpdate(player.dbId, { $inc: { score: points } }).exec();
                io.to(roomId).emit('roundSuccess', `${player.name} VENCEU A RODADA! (+${points})`);
                emitPlayerUpdates(roomId);
                clearInterval(room.timer);
                io.to(roomId).emit('roundEnded', room.currentWord);
                setTimeout(() => startRound(roomId), 5000);
            } else {
                points = Math.max(1, 11 - room.solversCount);
                player.score += points;
                User.findByIdAndUpdate(player.dbId, { $inc: { score: points } }).exec();
                socket.emit('roundSuccess', `+${points} PONTOS!`);
                emitPlayerUpdates(roomId);
                if (Object.values(room.players).every(pl => pl.solvedRound)) room.timeLeft = 2;
            }
        }
    });

    socket.on('leaveMatch', async (roomId) => {
        // Se a pessoa clicou em "Sair", é saída imediata, sem tempo de espera.
        await executePlayerExit(roomId, socket.id);
        socket.leave(roomId);
        socket.emit('matchLeft');
        const updatedUser = await User.findById(user._id);
        socket.emit('userDataUpdate', updatedUser);
    });

    // === DESCONEXÃO INTELIGENTE ===
    socket.on('disconnect', async () => {
        console.log(`⚠️ Conexão perdida: ${user.username} (ID: ${socket.id})`);
        
        // Verifica se o jogador está em alguma sala
        let foundRoomId = null;
        for (const rid in rooms) {
            if (rooms[rid].players[socket.id]) {
                foundRoomId = rid;
                break;
            }
        }

        if (foundRoomId) {
            // Se ele estava em uma sala, NÃO removemos agora.
            // Agendamos a remoção para daqui a 60 segundos.
            disconnectTimers[userId] = setTimeout(() => {
                console.log(`⏰ Tempo esgotado para ${user.username}. Removendo da sala.`);
                executePlayerExit(foundRoomId, socket.id);
                delete disconnectTimers[userId];
            }, RECONNECT_GRACE_PERIOD);
        }
    });
});

function startRound(roomId) {
    const room = rooms[roomId];
    if(!room) return;
    if (room.currentRound >= TOTAL_ROUNDS) { checkGameEnd(roomId); return; }

    room.currentRound++;
    room.currentWord = WORDS.length > 0 ? WORDS[Math.floor(Math.random() * WORDS.length)] : "TERMO";
    room.timeLeft = ROUND_TIME; room.solversCount = 0;
    Object.values(room.players).forEach(p => { p.solvedRound = false; p.roundAttempts = 0; });
    
    setupTimer(room);
    io.to(roomId).emit('newRound', { roundNumber: room.currentRound, totalRounds: TOTAL_ROUNDS, gameMode: room.gameMode });
}

function setupTimer(room) {
    clearInterval(room.timer);
    room.timer = setInterval(() => {
        room.timeLeft--;
        io.to(room.id).emit('timerUpdate', room.timeLeft);
        if (room.timeLeft <= 0) {
            clearInterval(room.timer);
            io.to(room.id).emit('roundEnded', room.currentWord);
            if(room.state === 'TIEBREAKER') setTimeout(() => startTiebreaker(room.id), 5000);
            else setTimeout(() => startRound(room.id), 5000);
        }
    }, 1000);
}

function checkGameEnd(roomId) {
    const room = rooms[roomId];
    if(!room) return;
    const players = Object.values(room.players).sort((a,b) => b.score - a.score);
    if (players.length > 1 && players[0].score === players[1].score) {
        room.state = 'TIEBREAKER';
        const maxScore = players[0].score;
        room.tiedPlayersIds = players.filter(p => p.score === maxScore).map(p => p.id);
        io.to(roomId).emit('tiebreakerAlert', { tiedPlayersIds: room.tiedPlayersIds });
        setTimeout(() => startTiebreaker(roomId), 5000);
    } else {
        endGameFinal(roomId);
    }
}

function startTiebreaker(roomId) {
    const room = rooms[roomId];
    if(!room) return;
    room.currentRound++; 
    room.currentWord = WORDS.length > 0 ? WORDS[Math.floor(Math.random() * WORDS.length)] : "TERMO";
    room.timeLeft = ROUND_TIME; room.solversCount = 0;
    Object.values(room.players).forEach(p => { p.solvedRound = false; p.roundAttempts = 0; });
    setupTimer(room);
    io.to(roomId).emit('tiebreakerRoundStarted', { tiedPlayersIds: room.tiedPlayersIds });
}

async function endGameFinal(roomId) {
    const room = rooms[roomId];
    if(!room) return;
    room.state = 'LOBBY'; room.currentRound = 0; room.solversCount = 0; room.tiedPlayersIds = [];
    clearInterval(room.timer);
    const players = Object.values(room.players).sort((a,b) => b.score - a.score);
    if(players.length > 0) await User.findByIdAndUpdate(players[0].dbId, { $inc: { wins: 1 } });
    io.to(roomId).emit('gameOver', players);
    Object.values(room.players).forEach(p => { p.score = 0; p.solvedRound = false; p.roundAttempts = 0; });
    emitRoomList();
    setTimeout(() => { io.to(roomId).emit('returnToLobby'); emitPlayerUpdates(roomId); }, 5000);
}

function calculateWordleResult(guess, target) {
    const res = Array(5).fill('absent');
    const targetArr = target.split(''); const guessArr = guess.split('');
    const targetFreq = {};
    targetArr.forEach(c => targetFreq[c] = (targetFreq[c] || 0) + 1);
    guessArr.forEach((c, i) => { if (c === targetArr[i]) { res[i] = 'correct'; targetFreq[c]--; } });
    guessArr.forEach((c, i) => { if (res[i] !== 'correct' && targetFreq[c] > 0) { res[i] = 'present'; targetFreq[c]--; } });
    return res;
}

const PORT = process.env.PORT || 3000;
server.listen(PORT, () => console.log(`Rodando na porta ${PORT}`));
